# Funding options for xg2g
# You can uncomment and configure these if you want to accept sponsorships

# github: [ManuGH]
# patreon: your_username
# ko_fi: your_username
# custom: ["https://your-donation-link.com"]
