changelog:
  categories:
    - title: Features
      labels:
        - "feature"
        - "enhancement"
    - title: Bug Fixes
      labels:
        - "bug"
        - "fix"
    - title: Security
      labels:
        - "security"
    - title: Performance
      labels:
        - "performance"
    - title: Documentation
      labels:
        - "documentation"
        - "docs"
    - title: CI and Maintenance
      labels:
        - "maintenance"
        - "chore"
        - "ci"
  exclude:
    labels:
      - "ignore-for-release"
      - "duplicate"
      - "invalid"
      - "wontfix"
