version: 2

# golangci-lint configuration file
# see https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: false # Skip tests to reduce noise on legacy test files

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosec
    - errcheck # Enabled for strict quality gates

linters-settings:
  staticcheck:
    checks: ["all"]
