version: 2

project_name: xg2g

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: xg2g-nogpu
    main: ./cmd/daemon
    binary: xg2g
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -mod=readonly
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    tags:
      - nogpu
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Skip unsupported combinations
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - "Merge pull request"
  groups:
    - title: "New Features"
      regexp: "^feat.*"
      order: 0
    - title: "Bug Fixes"
      regexp: "^fix.*"
      order: 1
    - title: "Performance Improvements"
      regexp: "^perf.*"
      order: 2
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: ManuGH
    name: xg2g
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## xg2g v{{ .Version }}

    ### 📦 Release Variants

    | Variant | Distribution | Audio Transcoding | Use Case |
    |---------|-------------|-------------------|----------|
    | **Lite** | CLI Binaries (below) | ❌ No | Linux servers, macOS, simple setups |
    | **Full** | Docker Images | ✅ Yes (Rust+FFmpeg) | iOS/Safari, production, all features |

    ### 🚀 Quick Start

    **Lite (CLI Binary):**
    ```bash
    # Download for your platform below, then:
    ./xg2g
    ```

    **Full (Docker - Recommended):**
    ```bash
    docker pull ghcr.io/manugh/xg2g:{{ .Version }}
    # or
    docker pull ghcr.io/manugh/xg2g:latest
    ```

    ### ⚠️ Lite vs Full Feature Matrix

    | Feature | Lite (Binaries) | Full (Docker) |
    |---------|----------------|---------------|
    | M3U Playlist Generation | ✅ | ✅ |
    | XMLTV EPG | ✅ | ✅ |
    | HDHomeRun Emulation | ✅ | ✅ |
    | Audio Transcoding (AC3/MP2 → AAC) | ❌ | ✅ |
    | iOS/Safari Compatibility | ❌ | ✅ |
    | Multi-arch Support | ✅ | ✅ |
    | Platforms | Linux, macOS, Windows | linux/amd64, linux/arm64 |

    **Need audio transcoding?** Use Docker images instead of CLI binaries.

    ### What's Changed
  footer: |
    ---

    **Installation:**

    Download the appropriate binary for your platform, extract it, and run:
    ```bash
    ./xg2g
    ```

    **Docker (recommended for full features):**
    ```bash
    docker pull ghcr.io/manugh/xg2g:{{ .Version }}
    ```

    **Full Changelog**: https://github.com/ManuGH/xg2g/compare/{{ .PreviousTag }}...{{ .Tag }}

# SBOM generation disabled (syft not installed in workflow)
# To enable: install syft in goreleaser.yml workflow before running goreleaser
# sboms:
#   - id: default
#     artifacts: archive
#     documents:
#       - "{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json"

# Sign artifacts
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - "--yes"
    artifacts: checksum
    output: true
