#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_EXAMPLE="${REPO_ROOT}/.env.example"
ENV_FILE="${REPO_ROOT}/.env"
WEBUI_DIR="${REPO_ROOT}/frontend/webui"
LIB_ENV="${REPO_ROOT}/backend/scripts/lib/env.sh"

source "${LIB_ENV}"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "missing required command: $1"
}

ensure_env_file() {
  if [[ -f "${ENV_FILE}" ]]; then
    echo "Using existing ${ENV_FILE}"
    return 0
  fi

  [[ -f "${ENV_EXAMPLE}" ]] || fail "missing ${ENV_EXAMPLE}"
  cp "${ENV_EXAMPLE}" "${ENV_FILE}"
  echo "Created ${ENV_FILE} from ${ENV_EXAMPLE}"
}

ensure_decision_secret() {
  if read_env_value "${ENV_FILE}" XG2G_DECISION_SECRET >/dev/null 2>&1; then
    return 0
  fi

  printf '\n# Generated by make install for local development\nXG2G_DECISION_SECRET=%s\n' "$(openssl rand -hex 32)" >> "${ENV_FILE}"
  echo "Added generated XG2G_DECISION_SECRET to ${ENV_FILE}"
}

install_webui_deps() {
  [[ -d "${WEBUI_DIR}" ]] || fail "missing WebUI directory: ${WEBUI_DIR}"
  (cd "${WEBUI_DIR}" && npm ci)
}

warn_placeholders() {
  local e2_host api_token

  e2_host="$(read_env_value "${ENV_FILE}" XG2G_E2_HOST 2>/dev/null || true)"
  api_token="$(read_env_value "${ENV_FILE}" XG2G_API_TOKEN 2>/dev/null || true)"

  if [[ "${e2_host}" == "http://192.168.1.100" ]]; then
    echo "NOTE: ${ENV_FILE} still contains the example XG2G_E2_HOST. Update it before real playback tests."
  fi
  if [[ "${api_token}" == "dev-token" ]]; then
    echo "NOTE: ${ENV_FILE} still uses the example API token. That is fine for local dev, but not for shared environments."
  fi
}

main() {
  need_cmd openssl
  need_cmd npm

  ensure_env_file
  ensure_decision_secret
  install_webui_deps
  warn_placeholders

  echo "✅ Local developer install complete."
  echo "Next steps:"
  echo "  1. Run 'make dev-tools' once per machine if you have not installed the pinned repo CLI tools yet"
  echo "  2. Start the default local stack with 'make start'"
  echo "  3. Use 'make dev-ui', 'make start-gpu', or 'make start-nvidia' only when you explicitly need those paths"
}

main "$@"
