// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	// #nosec G101
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ComponentStatusStatus.
const (
	ComponentStatusStatusError ComponentStatusStatus = "error"
	ComponentStatusStatusOk    ComponentStatusStatus = "ok"
)

// Defines values for EPGConfigSource.
const (
	EPGConfigSourceBouquet    EPGConfigSource = "bouquet"
	EPGConfigSourcePerService EPGConfigSource = "per-service"
)

// Defines values for EPGStatusStatus.
const (
	EPGStatusStatusMissing EPGStatusStatus = "missing"
	EPGStatusStatusOk      EPGStatusStatus = "ok"
)

// Defines values for StreamSessionState.
const (
	Active StreamSessionState = "active"
	Idle   StreamSessionState = "idle"
)

// Defines values for SystemHealthStatus.
const (
	Degraded SystemHealthStatus = "degraded"
	Error    SystemHealthStatus = "error"
	Ok       SystemHealthStatus = "ok"
)

// AppConfig defines model for AppConfig.
type AppConfig struct {
	Bouquets     *[]string        `json:"bouquets,omitempty"`
	DataDir      *string          `json:"dataDir,omitempty"`
	Epg          *EPGConfig       `json:"epg,omitempty"`
	FeatureFlags *FeatureFlags    `json:"featureFlags,omitempty"`
	LogLevel     *string          `json:"logLevel,omitempty"`
	OpenWebIF    *OpenWebIFConfig `json:"openWebIF,omitempty"`
	Picons       *PiconsConfig    `json:"picons,omitempty"`
	Version      *string          `json:"version,omitempty"`
}

// Bouquet defines model for Bouquet.
type Bouquet struct {
	Name     *string `json:"name,omitempty"`
	Services *int    `json:"services,omitempty"`
}

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus struct {
	LastCheck *time.Time             `json:"last_check,omitempty"`
	Status    *ComponentStatusStatus `json:"status,omitempty"`
}

// ComponentStatusStatus defines model for ComponentStatus.Status.
type ComponentStatusStatus string

// ConfigUpdate defines model for ConfigUpdate.
type ConfigUpdate struct {
	Bouquets     *[]string        `json:"bouquets,omitempty"`
	Epg          *EPGConfig       `json:"epg,omitempty"`
	FeatureFlags *FeatureFlags    `json:"featureFlags,omitempty"`
	OpenWebIF    *OpenWebIFConfig `json:"openWebIF,omitempty"`
	Picons       *PiconsConfig    `json:"picons,omitempty"`
}

// EPGConfig defines model for EPGConfig.
type EPGConfig struct {
	Days    *int             `json:"days,omitempty"`
	Enabled *bool            `json:"enabled,omitempty"`
	Source  *EPGConfigSource `json:"source,omitempty"`
}

// EPGConfigSource defines model for EPGConfig.Source.
type EPGConfigSource string

// EPGStatus defines model for EPGStatus.
type EPGStatus struct {
	MissingChannels *int             `json:"missing_channels,omitempty"`
	Status          *EPGStatusStatus `json:"status,omitempty"`
}

// EPGStatusStatus defines model for EPGStatus.Status.
type EPGStatusStatus string

// FeatureFlags defines model for FeatureFlags.
type FeatureFlags struct {
	InstantTune *bool `json:"instantTune,omitempty"`
}

// LogEntry defines model for LogEntry.
type LogEntry struct {
	Fields  *map[string]interface{} `json:"fields,omitempty"`
	Level   *string                 `json:"level,omitempty"`
	Message *string                 `json:"message,omitempty"`
	Time    *time.Time              `json:"time,omitempty"`
}

// OpenWebIFConfig defines model for OpenWebIFConfig.
type OpenWebIFConfig struct {
	BaseUrl    *string `json:"baseUrl,omitempty"`
	Password   *string `json:"password,omitempty"`
	StreamPort *int    `json:"streamPort,omitempty"`
	Username   *string `json:"username,omitempty"`
}

// PiconsConfig defines model for PiconsConfig.
type PiconsConfig struct {
	BaseUrl *string `json:"baseUrl,omitempty"`
}

// Service defines model for Service.
type Service struct {
	Enabled *bool   `json:"enabled,omitempty"`
	Group   *string `json:"group,omitempty"`
	Id      *string `json:"id,omitempty"`
	LogoUrl *string `json:"logo_url,omitempty"`
	Name    *string `json:"name,omitempty"`
	Number  *string `json:"number,omitempty"`

	// ServiceRef Service reference for streaming (extracted from M3U URL)
	ServiceRef *string `json:"service_ref,omitempty"`
}

// StreamSession defines model for StreamSession.
type StreamSession struct {
	ChannelName *string             `json:"channel_name,omitempty"`
	ClientIp    *string             `json:"client_ip,omitempty"`
	Id          *string             `json:"id,omitempty"`
	StartedAt   *time.Time          `json:"started_at,omitempty"`
	State       *StreamSessionState `json:"state,omitempty"`
}

// StreamSessionState defines model for StreamSession.State.
type StreamSessionState string

// SystemHealth defines model for SystemHealth.
type SystemHealth struct {
	Epg           *EPGStatus          `json:"epg,omitempty"`
	Receiver      *ComponentStatus    `json:"receiver,omitempty"`
	Status        *SystemHealthStatus `json:"status,omitempty"`
	UptimeSeconds *int64              `json:"uptime_seconds,omitempty"`
	Version       *string             `json:"version,omitempty"`
}

// SystemHealthStatus defines model for SystemHealth.Status.
type SystemHealthStatus string

// GetServicesParams defines parameters for GetServices.
type GetServicesParams struct {
	// Bouquet Filter by bouquet name
	Bouquet *string `form:"bouquet,omitempty" json:"bouquet,omitempty"`
}

// PostServicesIdToggleJSONBody defines parameters for PostServicesIdToggle.
type PostServicesIdToggleJSONBody struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// PostServicesIdToggleJSONRequestBody defines body for PostServicesIdToggle for application/json ContentType.
type PostServicesIdToggleJSONRequestBody PostServicesIdToggleJSONBody

// PutSystemConfigJSONRequestBody defines body for PutSystemConfig for application/json ContentType.
type PutSystemConfigJSONRequestBody = ConfigUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get recent logs
	// (GET /logs)
	GetLogs(w http.ResponseWriter, r *http.Request)
	// List all services (channels)
	// (GET /services)
	GetServices(w http.ResponseWriter, r *http.Request, params GetServicesParams)
	// List all bouquets
	// (GET /services/bouquets)
	GetServicesBouquets(w http.ResponseWriter, r *http.Request)
	// Toggle service enabled state
	// (POST /services/{id}/toggle)
	PostServicesIdToggle(w http.ResponseWriter, r *http.Request, id string)
	// List active streams
	// (GET /streams)
	GetStreams(w http.ResponseWriter, r *http.Request)
	// Terminate a stream session
	// (DELETE /streams/{id})
	DeleteStreamsId(w http.ResponseWriter, r *http.Request, id string)
	// Get system configuration
	// (GET /system/config)
	GetSystemConfig(w http.ResponseWriter, r *http.Request)
	// Update system configuration
	// (PUT /system/config)
	PutSystemConfig(w http.ResponseWriter, r *http.Request)
	// Get system health
	// (GET /system/health)
	GetSystemHealth(w http.ResponseWriter, r *http.Request)
	// Trigger data refresh (EPG/Channels)
	// (POST /system/refresh)
	PostSystemRefresh(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get recent logs
// (GET /logs)
func (_ Unimplemented) GetLogs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all services (channels)
// (GET /services)
func (_ Unimplemented) GetServices(w http.ResponseWriter, r *http.Request, params GetServicesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all bouquets
// (GET /services/bouquets)
func (_ Unimplemented) GetServicesBouquets(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Toggle service enabled state
// (POST /services/{id}/toggle)
func (_ Unimplemented) PostServicesIdToggle(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List active streams
// (GET /streams)
func (_ Unimplemented) GetStreams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Terminate a stream session
// (DELETE /streams/{id})
func (_ Unimplemented) DeleteStreamsId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get system configuration
// (GET /system/config)
func (_ Unimplemented) GetSystemConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update system configuration
// (PUT /system/config)
func (_ Unimplemented) PutSystemConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get system health
// (GET /system/health)
func (_ Unimplemented) GetSystemHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger data refresh (EPG/Channels)
// (POST /system/refresh)
func (_ Unimplemented) PostSystemRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLogs operation middleware
func (siw *ServerInterfaceWrapper) GetLogs(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLogs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServices operation middleware
func (siw *ServerInterfaceWrapper) GetServices(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServicesParams

	// ------------- Optional query parameter "bouquet" -------------

	err = runtime.BindQueryParameter("form", true, false, "bouquet", r.URL.Query(), &params.Bouquet)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bouquet", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServicesBouquets operation middleware
func (siw *ServerInterfaceWrapper) GetServicesBouquets(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServicesBouquets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostServicesIdToggle operation middleware
func (siw *ServerInterfaceWrapper) PostServicesIdToggle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostServicesIdToggle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStreams operation middleware
func (siw *ServerInterfaceWrapper) GetStreams(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStreams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteStreamsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteStreamsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteStreamsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemConfig operation middleware
func (siw *ServerInterfaceWrapper) GetSystemConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutSystemConfig operation middleware
func (siw *ServerInterfaceWrapper) PutSystemConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutSystemConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemHealth operation middleware
func (siw *ServerInterfaceWrapper) GetSystemHealth(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSystemRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostSystemRefresh(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSystemRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/logs", wrapper.GetLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services", wrapper.GetServices)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services/bouquets", wrapper.GetServicesBouquets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/services/{id}/toggle", wrapper.PostServicesIdToggle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/streams", wrapper.GetStreams)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/streams/{id}", wrapper.DeleteStreamsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/config", wrapper.GetSystemConfig)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/system/config", wrapper.PutSystemConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/health", wrapper.GetSystemHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/system/refresh", wrapper.PostSystemRefresh)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xYUW/bNhD+KwS3hxRw4yDtBsxvSZtkLjLMqBP0oQgMWjzLbClSOVJejMD/fSApWZJF",
	"2U635s0Kj8e77/t4d8wzTXSWawXKGjp6piZZQsb8z4s8/6DVQqTuI0edA1oBfmmui8cCwg5hIfM/7DoH",
	"OqLGolAp3QyqPzBEtnbfnFn2UWDUFnJ/zK8ICzqivwzrqIZlSMOryU0Zz2ZAF8BsgXAtWWoObbxu2m4G",
	"VOr0FlYgo4HoHNQXmI+vD3n9uzKsg8pFotXBcCbeqt61AjRCq0g0NYZ6/g0S66wvA/RdThTLIJqRAVyJ",
	"BJocCWUhBYyf8KEKeWqZLUz3JMmMnSVLSL67r4XGjFk6cvTCWysyoINIEFtfoIqMjr5S/Z0OKCBqpA+D",
	"YzIPiN3n7pz/S5KvKbvXVlYMwzqZDoCcraMSGVBQbC6BNxbnWktgyhOrC0ygSWzJBB3QHPBtqb4jOb6a",
	"3PSpLhPGCJXOkiVTCmRPrD06KzcfGcX1DsvtQIQylil7VyiIQRJzeKvTK2Vx3XW2ECC5/8U4F1ZoxeSk",
	"YWGxgIhD2Vu/MjCGpfFK4C/nkVc2lsauMLuXkBm4x3hgOTPmH408XqMsAssmGm2c1sIA9hS4WKCti/CC",
	"KGO+pqWAO272XosUdZFHUxVxBKRO9azowa63tqsimwPuK/szXy+eKQeToMit7zRVUgRhAQgqAbLQSAIL",
	"QqXkBJ4sssQCJwvUGfnr3T25/3z75jidTL2fKZiqr7WBK2/wrDerRApQdiZeBKCxDC3wGbMv60qt2sUS",
	"K1bOVHB5bM2aro2F7E9g0i4jKjmqw5RFbzOgCAmIVeB036bdLt1f+zikyDjwPe12QIvcYTQzkGgV6tEW",
	"QaHs7+9r9Bq38iWTi1dkUqCw66lLIaBzCQwBL4qA3Nx/XVcHf/pyRwdhIvW3y6/WgSytzenGORZqobsa",
	"v5iMvaqf0vOUnFwpkWbsnFhNJhKehp9AyvVCKDJB/bT2whZWOr/e/mIypo0E6fnp2elZ1cVZLuiIvjs9",
	"O33nuhyzS5/MUOrQL9IwnzkZMBfMmNMRvQF769YdxSbXygQEzs/O/J3QyoLy21ieS5H4jcNvJsAbWG/N",
	"NvvEse03nZHHwdWG6TMkoCyROiWgLDrZerKKLGOuY7nACW6NwuqwOVT2pTutbBxGyDKwgIaOvu4SdS2k",
	"BSTzNSlHB+Irg+OVjuhjAbimVQ1sTBc1Jrvie3gNjKu+cATEt8JYohdkC1obYL/MpNyuk5NqyHnTRnvY",
	"nHIPwX5Z2b4GGtWz5AVobHPpQaO1XkPwLPhmaHWaytCTtYnAMNFmi8OY3wXrjgy9vtz1reUluIfrsRDo",
	"WnsYvw4o7bEAYy81X78I1qOHiUgt3ezGuIlzvNP0fX8ghX9BcUfV+7P3/bOB0pYsdKH4DkEBzUqspIyc",
	"hF4auPL9f79IS5NXuamtceQIhV74KYCYsCMu0NKkTKOZtldogFVCGC/a6X/0fy8RGPOfpssWrlGifX7E",
	"AmZCHdBEMO3VROWCsBKTCr0SGj8jDZPtRN6rC29YTu7/URz7NFH/cyvCf1gpQmSRbhiyIUnbbEDzIlaK",
	"im5SP1Yx9o+DjX+OHF8gfrBaIfhpe1afcWzZ2gN0uzBF6tdYrZgUvIv7bzHrayZcWbKaGLaC3U0tTgNs",
	"PbQ25Lvczvj75Vu+BX6ifFvnRIANK6R8EfQqeFk5qHNEWCCY5YHW6m0/l6adPM+7bJS2pHylBY7/6Ldj",
	"EoHxNRGK5KhTBLObxh2KNAUknFlGyqjJydXkZvihMTw1nh2+tDYfHF8fXJ10fSw+l05Q8yLx0gzPAf88",
	"p0OWi+HqnG4eNv8GAAD//3Yjm/c+FwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
