// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ComponentStatusStatus.
const (
	ComponentStatusStatusError ComponentStatusStatus = "error"
	ComponentStatusStatusOk    ComponentStatusStatus = "ok"
)

// Defines values for DvrCapabilitiesSeriesMode.
const (
	Delegated DvrCapabilitiesSeriesMode = "delegated"
	Managed   DvrCapabilitiesSeriesMode = "managed"
	None      DvrCapabilitiesSeriesMode = "none"
)

// Defines values for EPGConfigSource.
const (
	EPGConfigSourceBouquet    EPGConfigSource = "bouquet"
	EPGConfigSourcePerService EPGConfigSource = "per-service"
)

// Defines values for EPGStatusStatus.
const (
	EPGStatusStatusMissing EPGStatusStatus = "missing"
	EPGStatusStatusOk      EPGStatusStatus = "ok"
)

// Defines values for IntentRequestType.
const (
	StreamStart IntentRequestType = "stream.start"
	StreamStop  IntentRequestType = "stream.stop"
)

// Defines values for PlaybackInfoMode.
const (
	DirectMp4 PlaybackInfoMode = "direct_mp4"
	Hls       PlaybackInfoMode = "hls"
)

// Defines values for RecordingBuildStatusAttemptMode.
const (
	Fast   RecordingBuildStatusAttemptMode = "fast"
	Robust RecordingBuildStatusAttemptMode = "robust"
)

// Defines values for RecordingBuildStatusState.
const (
	RecordingBuildStatusStateFAILED  RecordingBuildStatusState = "FAILED"
	RecordingBuildStatusStateIDLE    RecordingBuildStatusState = "IDLE"
	RecordingBuildStatusStateREADY   RecordingBuildStatusState = "READY"
	RecordingBuildStatusStateRUNNING RecordingBuildStatusState = "RUNNING"
)

// Defines values for SeriesRuleRunReportStatus.
const (
	Failed  SeriesRuleRunReportStatus = "failed"
	Partial SeriesRuleRunReportStatus = "partial"
	Success SeriesRuleRunReportStatus = "success"
)

// Defines values for SessionRecordReason.
const (
	SessionRecordReasonRBADREQUEST         SessionRecordReason = "R_BAD_REQUEST"
	SessionRecordReasonRCANCELLED          SessionRecordReason = "R_CANCELLED"
	SessionRecordReasonRCLIENTSTOP         SessionRecordReason = "R_CLIENT_STOP"
	SessionRecordReasonRFFMPEGSTARTFAILED  SessionRecordReason = "R_FFMPEG_START_FAILED"
	SessionRecordReasonRIDLETIMEOUT        SessionRecordReason = "R_IDLE_TIMEOUT"
	SessionRecordReasonRINVARIANTVIOLATION SessionRecordReason = "R_INVARIANT_VIOLATION"
	SessionRecordReasonRLEASEBUSY          SessionRecordReason = "R_LEASE_BUSY"
	SessionRecordReasonRLEASEEXPIRED       SessionRecordReason = "R_LEASE_EXPIRED"
	SessionRecordReasonRNONE               SessionRecordReason = "R_NONE"
	SessionRecordReasonRNOTFOUND           SessionRecordReason = "R_NOT_FOUND"
	SessionRecordReasonRPACKAGERFAILED     SessionRecordReason = "R_PACKAGER_FAILED"
	SessionRecordReasonRPROCESSENDED       SessionRecordReason = "R_PROCESS_ENDED"
	SessionRecordReasonRTUNEFAILED         SessionRecordReason = "R_TUNE_FAILED"
	SessionRecordReasonRTUNETIMEOUT        SessionRecordReason = "R_TUNE_TIMEOUT"
	SessionRecordReasonRUNKNOWN            SessionRecordReason = "R_UNKNOWN"
)

// Defines values for SessionRecordState.
const (
	SessionRecordStateCANCELLED SessionRecordState = "CANCELLED"
	SessionRecordStateDRAINING  SessionRecordState = "DRAINING"
	SessionRecordStateFAILED    SessionRecordState = "FAILED"
	SessionRecordStateNEW       SessionRecordState = "NEW"
	SessionRecordStatePRIMING   SessionRecordState = "PRIMING"
	SessionRecordStateREADY     SessionRecordState = "READY"
	SessionRecordStateSTARTING  SessionRecordState = "STARTING"
	SessionRecordStateSTOPPED   SessionRecordState = "STOPPED"
	SessionRecordStateSTOPPING  SessionRecordState = "STOPPING"
)

// Defines values for SessionResponseMode.
const (
	LIVE      SessionResponseMode = "LIVE"
	RECORDING SessionResponseMode = "RECORDING"
)

// Defines values for SessionResponseReason.
const (
	SessionResponseReasonRBADREQUEST         SessionResponseReason = "R_BAD_REQUEST"
	SessionResponseReasonRCANCELLED          SessionResponseReason = "R_CANCELLED"
	SessionResponseReasonRCLIENTSTOP         SessionResponseReason = "R_CLIENT_STOP"
	SessionResponseReasonRFFMPEGSTARTFAILED  SessionResponseReason = "R_FFMPEG_START_FAILED"
	SessionResponseReasonRIDLETIMEOUT        SessionResponseReason = "R_IDLE_TIMEOUT"
	SessionResponseReasonRINVARIANTVIOLATION SessionResponseReason = "R_INVARIANT_VIOLATION"
	SessionResponseReasonRLEASEBUSY          SessionResponseReason = "R_LEASE_BUSY"
	SessionResponseReasonRLEASEEXPIRED       SessionResponseReason = "R_LEASE_EXPIRED"
	SessionResponseReasonRNONE               SessionResponseReason = "R_NONE"
	SessionResponseReasonRNOTFOUND           SessionResponseReason = "R_NOT_FOUND"
	SessionResponseReasonRPACKAGERFAILED     SessionResponseReason = "R_PACKAGER_FAILED"
	SessionResponseReasonRPROCESSENDED       SessionResponseReason = "R_PROCESS_ENDED"
	SessionResponseReasonRTUNEFAILED         SessionResponseReason = "R_TUNE_FAILED"
	SessionResponseReasonRTUNETIMEOUT        SessionResponseReason = "R_TUNE_TIMEOUT"
	SessionResponseReasonRUNKNOWN            SessionResponseReason = "R_UNKNOWN"
)

// Defines values for SessionResponseState.
const (
	CANCELLED SessionResponseState = "CANCELLED"
	DRAINING  SessionResponseState = "DRAINING"
	FAILED    SessionResponseState = "FAILED"
	NEW       SessionResponseState = "NEW"
	PRIMING   SessionResponseState = "PRIMING"
	READY     SessionResponseState = "READY"
	STARTING  SessionResponseState = "STARTING"
	STOPPED   SessionResponseState = "STOPPED"
	STOPPING  SessionResponseState = "STOPPING"
)

// Defines values for StreamSessionState.
const (
	Active StreamSessionState = "active"
	Idle   StreamSessionState = "idle"
)

// Defines values for SystemHealthStatus.
const (
	Degraded SystemHealthStatus = "degraded"
	Error    SystemHealthStatus = "error"
	Ok       SystemHealthStatus = "ok"
)

// Defines values for TimerState.
const (
	TimerStateCompleted TimerState = "completed"
	TimerStateDisabled  TimerState = "disabled"
	TimerStateRecording TimerState = "recording"
	TimerStateScheduled TimerState = "scheduled"
	TimerStateUnknown   TimerState = "unknown"
)

// Defines values for TimerConflictType.
const (
	TimerConflictTypeDuplicate  TimerConflictType = "duplicate"
	TimerConflictTypeOverlap    TimerConflictType = "overlap"
	TimerConflictTypeTunerLimit TimerConflictType = "tuner_limit"
	TimerConflictTypeUnknown    TimerConflictType = "unknown"
)

// Defines values for TimerConflictPreviewRequestMode.
const (
	Conservative  TimerConflictPreviewRequestMode = "conservative"
	ReceiverAware TimerConflictPreviewRequestMode = "receiverAware"
)

// Defines values for TimerConflictPreviewResponseSuggestionsKind.
const (
	ReducePadding TimerConflictPreviewResponseSuggestionsKind = "reduce_padding"
	ShiftEnd      TimerConflictPreviewResponseSuggestionsKind = "shift_end"
	ShiftStart    TimerConflictPreviewResponseSuggestionsKind = "shift_start"
)

// Defines values for TimerCreateRequestAfterEvent.
const (
	Deepstandby TimerCreateRequestAfterEvent = "deepstandby"
	Default     TimerCreateRequestAfterEvent = "default"
	Nothing     TimerCreateRequestAfterEvent = "nothing"
	Standby     TimerCreateRequestAfterEvent = "standby"
)

// APIError defines model for APIError.
type APIError struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// Details Optional additional context
	Details interface{} `json:"details,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`

	// RequestId Request ID for debugging
	RequestId string `json:"request_id"`
}

// AppConfig defines model for AppConfig.
type AppConfig struct {
	Bouquets     *[]string        `json:"bouquets,omitempty"`
	DataDir      *string          `json:"dataDir,omitempty"`
	Epg          *EPGConfig       `json:"epg,omitempty"`
	FeatureFlags *FeatureFlags    `json:"featureFlags,omitempty"`
	LogLevel     *string          `json:"logLevel,omitempty"`
	OpenWebIF    *OpenWebIFConfig `json:"openWebIF,omitempty"`
	Picons       *PiconsConfig    `json:"picons,omitempty"`
	Version      *string          `json:"version,omitempty"`
}

// Bouquet defines model for Bouquet.
type Bouquet struct {
	Name     *string `json:"name,omitempty"`
	Services *int    `json:"services,omitempty"`
}

// Breadcrumb defines model for Breadcrumb.
type Breadcrumb struct {
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
}

// ComponentStatus defines model for ComponentStatus.
type ComponentStatus struct {
	LastCheck *time.Time             `json:"last_check,omitempty"`
	Status    *ComponentStatusStatus `json:"status,omitempty"`
}

// ComponentStatusStatus defines model for ComponentStatus.Status.
type ComponentStatusStatus string

// ConfigUpdate defines model for ConfigUpdate.
type ConfigUpdate struct {
	Bouquets     *[]string        `json:"bouquets,omitempty"`
	Epg          *EPGConfig       `json:"epg,omitempty"`
	FeatureFlags *FeatureFlags    `json:"featureFlags,omitempty"`
	OpenWebIF    *OpenWebIFConfig `json:"openWebIF,omitempty"`
	Picons       *PiconsConfig    `json:"picons,omitempty"`
}

// DirectoryItem defines model for DirectoryItem.
type DirectoryItem struct {
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
}

// DvrCapabilities defines model for DvrCapabilities.
type DvrCapabilities struct {
	Conflicts struct {
		Preview       *bool `json:"preview,omitempty"`
		ReceiverAware *bool `json:"receiverAware,omitempty"`
	} `json:"conflicts"`
	Series struct {
		DelegatedProvider *string                    `json:"delegatedProvider,omitempty"`
		Mode              *DvrCapabilitiesSeriesMode `json:"mode,omitempty"`
		Supported         *bool                      `json:"supported,omitempty"`
	} `json:"series"`
	Timers struct {
		Delete         *bool `json:"delete,omitempty"`
		Edit           *bool `json:"edit,omitempty"`
		ReadBackVerify *bool `json:"readBackVerify,omitempty"`
	} `json:"timers"`
}

// DvrCapabilitiesSeriesMode defines model for DvrCapabilities.Series.Mode.
type DvrCapabilitiesSeriesMode string

// EPGConfig defines model for EPGConfig.
type EPGConfig struct {
	Days    *int             `json:"days,omitempty"`
	Enabled *bool            `json:"enabled,omitempty"`
	Source  *EPGConfigSource `json:"source,omitempty"`
}

// EPGConfigSource defines model for EPGConfig.Source.
type EPGConfigSource string

// EPGStatus defines model for EPGStatus.
type EPGStatus struct {
	MissingChannels *int             `json:"missing_channels,omitempty"`
	Status          *EPGStatusStatus `json:"status,omitempty"`
}

// EPGStatusStatus defines model for EPGStatus.Status.
type EPGStatusStatus string

// FeatureFlags defines model for FeatureFlags.
type FeatureFlags struct {
	InstantTune *bool `json:"instantTune,omitempty"`
}

// IntentRequest defines model for IntentRequest.
type IntentRequest struct {
	// CorrelationId Optional correlation ID for end-to-end tracing
	CorrelationId *string `json:"correlationId,omitempty"`

	// IdempotencyKey Optional idempotency key for at-most-once semantics
	IdempotencyKey *string `json:"idempotencyKey,omitempty"`

	// Params Additional parameters
	Params *map[string]string `json:"params,omitempty"`

	// Profile Legacy alias for profileID (decode-only, will be removed in v3.2)
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Profile *string `json:"profile,omitempty"`

	// ProfileID Transcoding profile ID
	ProfileID *string `json:"profileID,omitempty"`

	// ServiceRef Required for stream.start. Enigma2 service reference (live playback only).
	ServiceRef *string `json:"serviceRef,omitempty"`

	// SessionId Required for stream.stop intent
	SessionId *openapi_types.UUID `json:"sessionId,omitempty"`
	Type      *IntentRequestType  `json:"type,omitempty"`
}

// IntentRequestType defines model for IntentRequest.Type.
type IntentRequestType string

// LogEntry defines model for LogEntry.
type LogEntry struct {
	Fields  *map[string]interface{} `json:"fields,omitempty"`
	Level   *string                 `json:"level,omitempty"`
	Message *string                 `json:"message,omitempty"`
	Time    *time.Time              `json:"time,omitempty"`
}

// NowNextEntry defines model for NowNextEntry.
type NowNextEntry struct {
	// End Unix timestamp (seconds)
	End int `json:"end"`

	// Start Unix timestamp (seconds)
	Start int    `json:"start"`
	Title string `json:"title"`
}

// NowNextItem defines model for NowNextItem.
type NowNextItem struct {
	Next       *NowNextEntry `json:"next,omitempty"`
	Now        *NowNextEntry `json:"now,omitempty"`
	ServiceRef string        `json:"service_ref"`
}

// NowNextRequest defines model for NowNextRequest.
type NowNextRequest struct {
	Services []string `json:"services"`
}

// NowNextResponse defines model for NowNextResponse.
type NowNextResponse struct {
	Items []NowNextItem `json:"items"`
}

// OpenWebIFConfig defines model for OpenWebIFConfig.
type OpenWebIFConfig struct {
	BaseUrl    *string `json:"baseUrl,omitempty"`
	Password   *string `json:"password,omitempty"`
	StreamPort *int    `json:"streamPort,omitempty"`
	Username   *string `json:"username,omitempty"`
}

// PiconsConfig defines model for PiconsConfig.
type PiconsConfig struct {
	BaseUrl *string `json:"baseUrl,omitempty"`
}

// PlaybackInfo defines model for PlaybackInfo.
type PlaybackInfo struct {
	Mode     PlaybackInfoMode `json:"mode"`
	Reason   *string          `json:"reason,omitempty"`
	Seekable *bool            `json:"seekable,omitempty"`
	Url      string           `json:"url"`
}

// PlaybackInfoMode defines model for PlaybackInfo.Mode.
type PlaybackInfoMode string

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Conflicts *[]TimerConflict        `json:"conflicts,omitempty"`
	Detail    *string                 `json:"detail,omitempty"`
	Fields    *map[string]interface{} `json:"fields,omitempty"`
	Instance  *string                 `json:"instance,omitempty"`
	Status    int                     `json:"status"`
	Title     string                  `json:"title"`
	Type      string                  `json:"type"`
}

// RecordingBuildStatus defines model for RecordingBuildStatus.
type RecordingBuildStatus struct {
	AttemptMode  *RecordingBuildStatusAttemptMode `json:"attempt_mode,omitempty"`
	Error        *string                          `json:"error,omitempty"`
	LastProgress *time.Time                       `json:"last_progress,omitempty"`

	// ProgressiveReady True if a progressive (timeshift) playlist is playable.
	ProgressiveReady *bool                     `json:"progressive_ready,omitempty"`
	SegmentCount     *int                      `json:"segment_count,omitempty"`
	StartedAt        *time.Time                `json:"started_at,omitempty"`
	State            RecordingBuildStatusState `json:"state"`
}

// RecordingBuildStatusAttemptMode defines model for RecordingBuildStatus.AttemptMode.
type RecordingBuildStatusAttemptMode string

// RecordingBuildStatusState defines model for RecordingBuildStatus.State.
type RecordingBuildStatusState string

// RecordingItem defines model for RecordingItem.
type RecordingItem struct {
	// BeginUnixSeconds Recording start time as UNIX seconds.
	BeginUnixSeconds *int64  `json:"begin_unix_seconds,omitempty"`
	Description      *string `json:"description,omitempty"`

	// DurationSeconds Recording duration in seconds, if known.
	DurationSeconds *int64  `json:"duration_seconds,omitempty"`
	Filename        *string `json:"filename,omitempty"`

	// Length Human-readable duration string for display only.
	Length *string `json:"length,omitempty"`

	// RecordingId Base64url-encoded recording ID (RFC 4648, unpadded) to use for /recordings/{recordingId}.
	RecordingId *string `json:"recording_id,omitempty"`

	// ServiceRef Legacy receiver service reference (read-only).
	ServiceRef *string `json:"service_ref,omitempty"`
	Title      *string `json:"title,omitempty"`
}

// RecordingResponse defines model for RecordingResponse.
type RecordingResponse struct {
	Breadcrumbs *[]Breadcrumb    `json:"breadcrumbs,omitempty"`
	CurrentPath *string          `json:"current_path,omitempty"`
	CurrentRoot *string          `json:"current_root,omitempty"`
	Directories *[]DirectoryItem `json:"directories,omitempty"`
	Recordings  *[]RecordingItem `json:"recordings,omitempty"`
	Roots       *[]RecordingRoot `json:"roots,omitempty"`
}

// RecordingRoot defines model for RecordingRoot.
type RecordingRoot struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// RecordingStatus defines model for RecordingStatus.
type RecordingStatus struct {
	IsRecording bool    `json:"isRecording"`
	ServiceName *string `json:"serviceName,omitempty"`
}

// RuleSnapshot defines model for RuleSnapshot.
type RuleSnapshot struct {
	ChannelRef  *string `json:"channelRef,omitempty"`
	Days        *[]int  `json:"days,omitempty"`
	Enabled     *bool   `json:"enabled,omitempty"`
	Id          *string `json:"id,omitempty"`
	Keyword     *string `json:"keyword,omitempty"`
	Priority    *int    `json:"priority,omitempty"`
	StartWindow *string `json:"startWindow,omitempty"`
}

// RunConflict defines model for RunConflict.
type RunConflict struct {
	Begin           *int64  `json:"begin,omitempty"`
	BlockingTimerId *string `json:"blockingTimerId,omitempty"`
	End             *int64  `json:"end,omitempty"`
	Message         *string `json:"message,omitempty"`
	OverlapSeconds  *int64  `json:"overlapSeconds,omitempty"`
	ServiceRef      *string `json:"serviceRef,omitempty"`
	Title           *string `json:"title,omitempty"`
}

// RunDecision defines model for RunDecision.
type RunDecision struct {
	Action      *string   `json:"action,omitempty"`
	Begin       *int64    `json:"begin,omitempty"`
	Details     *string   `json:"details,omitempty"`
	End         *int64    `json:"end,omitempty"`
	MatchReason *[]string `json:"matchReason,omitempty"`
	Reason      *string   `json:"reason,omitempty"`
	ServiceRef  *string   `json:"serviceRef,omitempty"`
	TimerId     *string   `json:"timerId,omitempty"`
	Title       *string   `json:"title,omitempty"`
}

// RunError defines model for RunError.
type RunError struct {
	At        *time.Time `json:"at,omitempty"`
	Message   *string    `json:"message,omitempty"`
	Retryable *bool      `json:"retryable,omitempty"`
	Type      *string    `json:"type,omitempty"`
}

// RunSummary defines model for RunSummary.
type RunSummary struct {
	EpgItemsMatched             *int  `json:"epgItemsMatched,omitempty"`
	EpgItemsScanned             *int  `json:"epgItemsScanned,omitempty"`
	MaxMatchesScannedPerRuleHit *bool `json:"maxMatchesScannedPerRuleHit,omitempty"`
	MaxTimersGlobalPerRunHit    *bool `json:"maxTimersGlobalPerRunHit,omitempty"`
	ReceiverUnreachable         *bool `json:"receiverUnreachable,omitempty"`
	TimersAttempted             *int  `json:"timersAttempted,omitempty"`
	TimersConflicted            *int  `json:"timersConflicted,omitempty"`
	TimersCreated               *int  `json:"timersCreated,omitempty"`
	TimersErrored               *int  `json:"timersErrored,omitempty"`
	TimersSkipped               *int  `json:"timersSkipped,omitempty"`
}

// SeriesRule defines model for SeriesRule.
type SeriesRule struct {
	// ChannelRef Optional service reference to restrict rule
	ChannelRef *string `json:"channel_ref,omitempty"`

	// Days Days of week (0=Sunday)
	Days    *[]int  `json:"days,omitempty"`
	Enabled *bool   `json:"enabled,omitempty"`
	Id      *string `json:"id,omitempty"`

	// Keyword Search term or regex for event title
	Keyword        *string     `json:"keyword,omitempty"`
	LastRunAt      *time.Time  `json:"lastRunAt,omitempty"`
	LastRunStatus  *string     `json:"lastRunStatus,omitempty"`
	LastRunSummary *RunSummary `json:"lastRunSummary,omitempty"`
	Priority       *int        `json:"priority,omitempty"`

	// StartWindow Time window HHMM-HHMM
	StartWindow *string `json:"start_window,omitempty"`
}

// SeriesRuleRunReport defines model for SeriesRuleRunReport.
type SeriesRuleRunReport struct {
	Conflicts  *[]RunConflict             `json:"conflicts,omitempty"`
	Decisions  *[]RunDecision             `json:"decisions,omitempty"`
	DurationMs *int64                     `json:"durationMs,omitempty"`
	Errors     *[]RunError                `json:"errors,omitempty"`
	FinishedAt *time.Time                 `json:"finishedAt,omitempty"`
	RuleId     *string                    `json:"ruleId,omitempty"`
	RunId      *string                    `json:"runId,omitempty"`
	Snapshot   *RuleSnapshot              `json:"snapshot,omitempty"`
	StartedAt  *time.Time                 `json:"startedAt,omitempty"`
	Status     *SeriesRuleRunReportStatus `json:"status,omitempty"`
	Summary    *RunSummary                `json:"summary,omitempty"`
	Trigger    *string                    `json:"trigger,omitempty"`
	WindowFrom *int64                     `json:"windowFrom,omitempty"`
	WindowTo   *int64                     `json:"windowTo,omitempty"`
}

// SeriesRuleRunReportStatus defines model for SeriesRuleRunReport.Status.
type SeriesRuleRunReportStatus string

// SeriesRuleUpdate defines model for SeriesRuleUpdate.
type SeriesRuleUpdate struct {
	// ChannelRef Optional service reference to restrict rule
	ChannelRef *string `json:"channel_ref,omitempty"`

	// Days Days of week (0=Sunday)
	Days    *[]int `json:"days,omitempty"`
	Enabled bool   `json:"enabled"`

	// Keyword Search term or regex for event title
	Keyword  string `json:"keyword"`
	Priority int    `json:"priority"`

	// StartWindow Time window HHMM-HHMM
	StartWindow *string `json:"start_window,omitempty"`
}

// Service defines model for Service.
type Service struct {
	Enabled *bool   `json:"enabled,omitempty"`
	Group   *string `json:"group,omitempty"`
	Id      *string `json:"id,omitempty"`
	LogoUrl *string `json:"logo_url,omitempty"`
	Name    *string `json:"name,omitempty"`
	Number  *string `json:"number,omitempty"`

	// ServiceRef Service reference for streaming (extracted from M3U URL)
	ServiceRef *string `json:"service_ref,omitempty"`
}

// SessionRecord defines model for SessionRecord.
type SessionRecord struct {
	ContextData    *map[string]string      `json:"contextData,omitempty"`
	CorrelationId  *string                 `json:"correlationId,omitempty"`
	CreatedAtUnix  *int64                  `json:"createdAtUnix,omitempty"`
	LastAccessUnix *int64                  `json:"lastAccessUnix,omitempty"`
	Profile        *map[string]interface{} `json:"profile,omitempty"`

	// Reason Reason code; R_LEASE_BUSY means capacity rejection (no tuner available), not a system fault.
	Reason       *SessionRecordReason `json:"reason,omitempty"`
	ReasonDetail *string              `json:"reasonDetail,omitempty"`
	ServiceRef   *string              `json:"serviceRef,omitempty"`
	SessionId    *openapi_types.UUID  `json:"sessionId,omitempty"`

	// State Session lifecycle state. READY guarantees a playable HLS stream (playlist + at least one segment,
	// atomically published). PRIMING means FFmpeg is running but content is not yet playable.
	State         *SessionRecordState `json:"state,omitempty"`
	TunerID       *string             `json:"tunerID,omitempty"`
	UpdatedAtUnix *int64              `json:"updatedAtUnix,omitempty"`
}

// SessionRecordReason Reason code; R_LEASE_BUSY means capacity rejection (no tuner available), not a system fault.
type SessionRecordReason string

// SessionRecordState Session lifecycle state. READY guarantees a playable HLS stream (playlist + at least one segment,
// atomically published). PRIMING means FFmpeg is running but content is not yet playable.
type SessionRecordState string

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	CorrelationId *string `json:"correlationId,omitempty"`

	// DurationSeconds DVR window length for live sessions, in seconds.
	DurationSeconds *float32 `json:"durationSeconds,omitempty"`

	// LiveEdgeSeconds Current live edge position in seconds (live only).
	LiveEdgeSeconds *float32 `json:"liveEdgeSeconds,omitempty"`

	// Mode Playback mode for the session.
	Mode *SessionResponseMode `json:"mode,omitempty"`

	// PlaybackUrl Playback URL for the HLS playlist.
	PlaybackUrl *string `json:"playbackUrl,omitempty"`
	Profile     *string `json:"profile,omitempty"`

	// Reason Reason code; R_LEASE_BUSY means capacity rejection (no tuner available), not a system fault.
	Reason       *SessionResponseReason `json:"reason,omitempty"`
	ReasonDetail *string                `json:"reasonDetail,omitempty"`

	// SeekableEndSeconds Latest seekable position in seconds.
	SeekableEndSeconds *float32 `json:"seekableEndSeconds,omitempty"`

	// SeekableStartSeconds Earliest seekable position in seconds.
	SeekableStartSeconds *float32           `json:"seekableStartSeconds,omitempty"`
	ServiceRef           *string            `json:"serviceRef,omitempty"`
	SessionId            openapi_types.UUID `json:"sessionId"`

	// State Session lifecycle state. READY guarantees a playable HLS stream (playlist + at least one segment,
	// atomically published). PRIMING means FFmpeg is running but content is not yet playable.
	State       SessionResponseState `json:"state"`
	UpdatedAtMs *int                 `json:"updatedAtMs,omitempty"`
}

// SessionResponseMode Playback mode for the session.
type SessionResponseMode string

// SessionResponseReason Reason code; R_LEASE_BUSY means capacity rejection (no tuner available), not a system fault.
type SessionResponseReason string

// SessionResponseState Session lifecycle state. READY guarantees a playable HLS stream (playlist + at least one segment,
// atomically published). PRIMING means FFmpeg is running but content is not yet playable.
type SessionResponseState string

// StreamSession defines model for StreamSession.
type StreamSession struct {
	ChannelName *string             `json:"channel_name,omitempty"`
	ClientIp    *string             `json:"client_ip,omitempty"`
	Id          *string             `json:"id,omitempty"`
	StartedAt   *time.Time          `json:"started_at,omitempty"`
	State       *StreamSessionState `json:"state,omitempty"`
}

// StreamSessionState defines model for StreamSession.State.
type StreamSessionState string

// SystemHealth defines model for SystemHealth.
type SystemHealth struct {
	Epg           *EPGStatus          `json:"epg,omitempty"`
	Receiver      *ComponentStatus    `json:"receiver,omitempty"`
	Status        *SystemHealthStatus `json:"status,omitempty"`
	UptimeSeconds *int64              `json:"uptime_seconds,omitempty"`
	Version       *string             `json:"version,omitempty"`
}

// SystemHealthStatus defines model for SystemHealth.Status.
type SystemHealthStatus string

// Timer defines model for Timer.
type Timer struct {
	Begin         int64                   `json:"begin"`
	CreatedAt     *time.Time              `json:"createdAt,omitempty"`
	Description   *string                 `json:"description,omitempty"`
	End           int64                   `json:"end"`
	Name          string                  `json:"name"`
	ReceiverState *map[string]interface{} `json:"receiverState,omitempty"`
	ServiceName   *string                 `json:"serviceName,omitempty"`
	ServiceRef    string                  `json:"serviceRef"`
	State         TimerState              `json:"state"`
	TimerId       string                  `json:"timerId"`
	UpdatedAt     *time.Time              `json:"updatedAt,omitempty"`
}

// TimerState defines model for Timer.State.
type TimerState string

// TimerConflict defines model for TimerConflict.
type TimerConflict struct {
	BlockingTimer  Timer             `json:"blockingTimer"`
	Message        *string           `json:"message,omitempty"`
	OverlapSeconds *int              `json:"overlapSeconds,omitempty"`
	Type           TimerConflictType `json:"type"`
}

// TimerConflictType defines model for TimerConflict.Type.
type TimerConflictType string

// TimerConflictPreviewRequest defines model for TimerConflictPreviewRequest.
type TimerConflictPreviewRequest struct {
	Mode     *TimerConflictPreviewRequestMode `json:"mode,omitempty"`
	Proposed TimerCreateRequest               `json:"proposed"`
}

// TimerConflictPreviewRequestMode defines model for TimerConflictPreviewRequest.Mode.
type TimerConflictPreviewRequestMode string

// TimerConflictPreviewResponse defines model for TimerConflictPreviewResponse.
type TimerConflictPreviewResponse struct {
	CanSchedule bool            `json:"canSchedule"`
	Conflicts   []TimerConflict `json:"conflicts"`
	Suggestions *[]struct {
		Kind          *TimerConflictPreviewResponseSuggestionsKind `json:"kind,omitempty"`
		Note          *string                                      `json:"note,omitempty"`
		ProposedBegin *int64                                       `json:"proposedBegin,omitempty"`
		ProposedEnd   *int64                                       `json:"proposedEnd,omitempty"`
	} `json:"suggestions,omitempty"`
}

// TimerConflictPreviewResponseSuggestionsKind defines model for TimerConflictPreviewResponse.Suggestions.Kind.
type TimerConflictPreviewResponseSuggestionsKind string

// TimerCreateRequest defines model for TimerCreateRequest.
type TimerCreateRequest struct {
	AfterEvent       *TimerCreateRequestAfterEvent `json:"afterEvent,omitempty"`
	Begin            int64                         `json:"begin"`
	Description      *string                       `json:"description,omitempty"`
	Enabled          *bool                         `json:"enabled,omitempty"`
	End              int64                         `json:"end"`
	IdempotencyKey   *string                       `json:"idempotencyKey,omitempty"`
	JustPlay         *bool                         `json:"justPlay,omitempty"`
	Name             string                        `json:"name"`
	PaddingAfterSec  *int                          `json:"paddingAfterSec,omitempty"`
	PaddingBeforeSec *int                          `json:"paddingBeforeSec,omitempty"`
	ServiceRef       string                        `json:"serviceRef"`
}

// TimerCreateRequestAfterEvent defines model for TimerCreateRequest.AfterEvent.
type TimerCreateRequestAfterEvent string

// TimerList defines model for TimerList.
type TimerList struct {
	Items []Timer `json:"items"`
}

// TimerPatchRequest defines model for TimerPatchRequest.
type TimerPatchRequest struct {
	Begin            *int64  `json:"begin,omitempty"`
	Description      *string `json:"description,omitempty"`
	Enabled          *bool   `json:"enabled,omitempty"`
	End              *int64  `json:"end,omitempty"`
	Name             *string `json:"name,omitempty"`
	PaddingAfterSec  *int    `json:"paddingAfterSec,omitempty"`
	PaddingBeforeSec *int    `json:"paddingBeforeSec,omitempty"`
}

// GetEpgParams defines parameters for GetEpg.
type GetEpgParams struct {
	// From Start timestamp (unix seconds)
	From *int `form:"from,omitempty" json:"from,omitempty"`

	// To End timestamp (unix seconds)
	To *int `form:"to,omitempty" json:"to,omitempty"`

	// Bouquet Filter by bouquet name
	Bouquet *string `form:"bouquet,omitempty" json:"bouquet,omitempty"`

	// Q Filter by search query
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// GetRecordingsParams defines parameters for GetRecordings.
type GetRecordingsParams struct {
	// Root Root location ID
	Root *string `form:"root,omitempty" json:"root,omitempty"`

	// Path Relative path
	Path *string `form:"path,omitempty" json:"path,omitempty"`
}

// RunAllSeriesRulesParams defines parameters for RunAllSeriesRules.
type RunAllSeriesRulesParams struct {
	Trigger *string `form:"trigger,omitempty" json:"trigger,omitempty"`
}

// RunSeriesRuleParams defines parameters for RunSeriesRule.
type RunSeriesRuleParams struct {
	Trigger *string `form:"trigger,omitempty" json:"trigger,omitempty"`
}

// GetServicesParams defines parameters for GetServices.
type GetServicesParams struct {
	// Bouquet Filter by bouquet name
	Bouquet *string `form:"bouquet,omitempty" json:"bouquet,omitempty"`
}

// PostServicesIdToggleJSONBody defines parameters for PostServicesIdToggle.
type PostServicesIdToggleJSONBody struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	// Offset Pagination offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Pagination limit (max 1000)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetTimersParams defines parameters for GetTimers.
type GetTimersParams struct {
	State *string `form:"state,omitempty" json:"state,omitempty"`
	From  *int    `form:"from,omitempty" json:"from,omitempty"`
}

// CreateIntentJSONRequestBody defines body for CreateIntent for application/json ContentType.
type CreateIntentJSONRequestBody = IntentRequest

// CreateSeriesRuleJSONRequestBody defines body for CreateSeriesRule for application/json ContentType.
type CreateSeriesRuleJSONRequestBody = SeriesRule

// UpdateSeriesRuleJSONRequestBody defines body for UpdateSeriesRule for application/json ContentType.
type UpdateSeriesRuleJSONRequestBody = SeriesRuleUpdate

// PostServicesNowNextJSONRequestBody defines body for PostServicesNowNext for application/json ContentType.
type PostServicesNowNextJSONRequestBody = NowNextRequest

// PostServicesIdToggleJSONRequestBody defines body for PostServicesIdToggle for application/json ContentType.
type PostServicesIdToggleJSONRequestBody PostServicesIdToggleJSONBody

// PutSystemConfigJSONRequestBody defines body for PutSystemConfig for application/json ContentType.
type PutSystemConfigJSONRequestBody = ConfigUpdate

// AddTimerJSONRequestBody defines body for AddTimer for application/json ContentType.
type AddTimerJSONRequestBody = TimerCreateRequest

// PreviewConflictsJSONRequestBody defines body for PreviewConflicts for application/json ContentType.
type PreviewConflictsJSONRequestBody = TimerConflictPreviewRequest

// UpdateTimerJSONRequestBody defines body for UpdateTimer for application/json ContentType.
type UpdateTimerJSONRequestBody = TimerPatchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create session cookie
	// (POST /auth/session)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// Get DVR capabilities
	// (GET /dvr/capabilities)
	GetDvrCapabilities(w http.ResponseWriter, r *http.Request)
	// Get DVR recording status
	// (GET /dvr/status)
	GetDvrStatus(w http.ResponseWriter, r *http.Request)
	// Get EPG data
	// (GET /epg)
	GetEpg(w http.ResponseWriter, r *http.Request, params GetEpgParams)
	// Create stream intent (start or stop session)
	// (POST /intents)
	CreateIntent(w http.ResponseWriter, r *http.Request)
	// Get recent logs
	// (GET /logs)
	GetLogs(w http.ResponseWriter, r *http.Request)
	// Browse recordings
	// (GET /recordings)
	GetRecordings(w http.ResponseWriter, r *http.Request, params GetRecordingsParams)
	// Delete a recording
	// (DELETE /recordings/{recordingId})
	DeleteRecording(w http.ResponseWriter, r *http.Request, recordingId string)
	// Get playback strategy for a recording
	// (GET /recordings/{recordingId}/playback)
	GetRecordingPlaybackInfo(w http.ResponseWriter, r *http.Request, recordingId string)
	// Get VOD HLS playlist for a recording
	// (GET /recordings/{recordingId}/playlist.m3u8)
	GetRecordingHLSPlaylist(w http.ResponseWriter, r *http.Request, recordingId string)
	// Get recording build status
	// (GET /recordings/{recordingId}/status)
	GetRecordingsRecordingIdStatus(w http.ResponseWriter, r *http.Request, recordingId string)
	// Stream recording as MP4 (Direct VOD)
	// (GET /recordings/{recordingId}/stream.mp4)
	StreamRecordingDirect(w http.ResponseWriter, r *http.Request, recordingId string)
	// Get timeshift HLS playlist for a recording
	// (GET /recordings/{recordingId}/timeshift.m3u8)
	GetRecordingHLSTimeshift(w http.ResponseWriter, r *http.Request, recordingId string)
	// Get HLS segment for a recording
	// (GET /recordings/{recordingId}/{segment})
	GetRecordingHLSCustomSegment(w http.ResponseWriter, r *http.Request, recordingId string, segment string)
	// List all series recording rules
	// (GET /series-rules)
	GetSeriesRules(w http.ResponseWriter, r *http.Request)
	// Create a new series rule
	// (POST /series-rules)
	CreateSeriesRule(w http.ResponseWriter, r *http.Request)
	// Run all enabled series rules immediately
	// (POST /series-rules/run)
	RunAllSeriesRules(w http.ResponseWriter, r *http.Request, params RunAllSeriesRulesParams)
	// Delete a series rule
	// (DELETE /series-rules/{id})
	DeleteSeriesRule(w http.ResponseWriter, r *http.Request, id string)
	// Update an existing series rule
	// (PUT /series-rules/{id})
	UpdateSeriesRule(w http.ResponseWriter, r *http.Request, id string)
	// Run a specific series rule immediately
	// (POST /series-rules/{id}/run)
	RunSeriesRule(w http.ResponseWriter, r *http.Request, id string, params RunSeriesRuleParams)
	// List all services (channels)
	// (GET /services)
	GetServices(w http.ResponseWriter, r *http.Request, params GetServicesParams)
	// List all bouquets
	// (GET /services/bouquets)
	GetServicesBouquets(w http.ResponseWriter, r *http.Request)
	// Get now/next EPG for a list of services
	// (POST /services/now-next)
	PostServicesNowNext(w http.ResponseWriter, r *http.Request)
	// Toggle service enabled state
	// (POST /services/{id}/toggle)
	PostServicesIdToggle(w http.ResponseWriter, r *http.Request, id string)
	// List all sessions (admin only)
	// (GET /sessions)
	ListSessions(w http.ResponseWriter, r *http.Request, params ListSessionsParams)
	// Get session state
	// (GET /sessions/{sessionID})
	GetSessionState(w http.ResponseWriter, r *http.Request, sessionID openapi_types.UUID)
	// Serve HLS playlist or segment
	// (GET /sessions/{sessionID}/hls/{filename})
	ServeHLS(w http.ResponseWriter, r *http.Request, sessionID openapi_types.UUID, filename string)
	// List active streams
	// (GET /streams)
	GetStreams(w http.ResponseWriter, r *http.Request)
	// Terminate a stream session
	// (DELETE /streams/{id})
	DeleteStreamsId(w http.ResponseWriter, r *http.Request, id string)
	// Get system configuration
	// (GET /system/config)
	GetSystemConfig(w http.ResponseWriter, r *http.Request)
	// Update system configuration
	// (PUT /system/config)
	PutSystemConfig(w http.ResponseWriter, r *http.Request)
	// Get system health
	// (GET /system/health)
	GetSystemHealth(w http.ResponseWriter, r *http.Request)
	// Get minimal system health
	// (GET /system/healthz)
	GetSystemHealthz(w http.ResponseWriter, r *http.Request)
	// Trigger data refresh (EPG/Channels)
	// (POST /system/refresh)
	PostSystemRefresh(w http.ResponseWriter, r *http.Request)
	// List all timers
	// (GET /timers)
	GetTimers(w http.ResponseWriter, r *http.Request, params GetTimersParams)
	// Create a timer
	// (POST /timers)
	AddTimer(w http.ResponseWriter, r *http.Request)
	// Preview conflicts
	// (POST /timers/conflicts:preview)
	PreviewConflicts(w http.ResponseWriter, r *http.Request)
	// Delete timer
	// (DELETE /timers/{timerId})
	DeleteTimer(w http.ResponseWriter, r *http.Request, timerId string)
	// Get timer
	// (GET /timers/{timerId})
	GetTimer(w http.ResponseWriter, r *http.Request, timerId string)
	// Edit timer
	// (PATCH /timers/{timerId})
	UpdateTimer(w http.ResponseWriter, r *http.Request, timerId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Create session cookie
// (POST /auth/session)
func (_ Unimplemented) CreateSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get DVR capabilities
// (GET /dvr/capabilities)
func (_ Unimplemented) GetDvrCapabilities(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get DVR recording status
// (GET /dvr/status)
func (_ Unimplemented) GetDvrStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get EPG data
// (GET /epg)
func (_ Unimplemented) GetEpg(w http.ResponseWriter, r *http.Request, params GetEpgParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create stream intent (start or stop session)
// (POST /intents)
func (_ Unimplemented) CreateIntent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get recent logs
// (GET /logs)
func (_ Unimplemented) GetLogs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Browse recordings
// (GET /recordings)
func (_ Unimplemented) GetRecordings(w http.ResponseWriter, r *http.Request, params GetRecordingsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a recording
// (DELETE /recordings/{recordingId})
func (_ Unimplemented) DeleteRecording(w http.ResponseWriter, r *http.Request, recordingId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get playback strategy for a recording
// (GET /recordings/{recordingId}/playback)
func (_ Unimplemented) GetRecordingPlaybackInfo(w http.ResponseWriter, r *http.Request, recordingId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get VOD HLS playlist for a recording
// (GET /recordings/{recordingId}/playlist.m3u8)
func (_ Unimplemented) GetRecordingHLSPlaylist(w http.ResponseWriter, r *http.Request, recordingId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get recording build status
// (GET /recordings/{recordingId}/status)
func (_ Unimplemented) GetRecordingsRecordingIdStatus(w http.ResponseWriter, r *http.Request, recordingId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stream recording as MP4 (Direct VOD)
// (GET /recordings/{recordingId}/stream.mp4)
func (_ Unimplemented) StreamRecordingDirect(w http.ResponseWriter, r *http.Request, recordingId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get timeshift HLS playlist for a recording
// (GET /recordings/{recordingId}/timeshift.m3u8)
func (_ Unimplemented) GetRecordingHLSTimeshift(w http.ResponseWriter, r *http.Request, recordingId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get HLS segment for a recording
// (GET /recordings/{recordingId}/{segment})
func (_ Unimplemented) GetRecordingHLSCustomSegment(w http.ResponseWriter, r *http.Request, recordingId string, segment string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all series recording rules
// (GET /series-rules)
func (_ Unimplemented) GetSeriesRules(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new series rule
// (POST /series-rules)
func (_ Unimplemented) CreateSeriesRule(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Run all enabled series rules immediately
// (POST /series-rules/run)
func (_ Unimplemented) RunAllSeriesRules(w http.ResponseWriter, r *http.Request, params RunAllSeriesRulesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a series rule
// (DELETE /series-rules/{id})
func (_ Unimplemented) DeleteSeriesRule(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing series rule
// (PUT /series-rules/{id})
func (_ Unimplemented) UpdateSeriesRule(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Run a specific series rule immediately
// (POST /series-rules/{id}/run)
func (_ Unimplemented) RunSeriesRule(w http.ResponseWriter, r *http.Request, id string, params RunSeriesRuleParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all services (channels)
// (GET /services)
func (_ Unimplemented) GetServices(w http.ResponseWriter, r *http.Request, params GetServicesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all bouquets
// (GET /services/bouquets)
func (_ Unimplemented) GetServicesBouquets(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get now/next EPG for a list of services
// (POST /services/now-next)
func (_ Unimplemented) PostServicesNowNext(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Toggle service enabled state
// (POST /services/{id}/toggle)
func (_ Unimplemented) PostServicesIdToggle(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all sessions (admin only)
// (GET /sessions)
func (_ Unimplemented) ListSessions(w http.ResponseWriter, r *http.Request, params ListSessionsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get session state
// (GET /sessions/{sessionID})
func (_ Unimplemented) GetSessionState(w http.ResponseWriter, r *http.Request, sessionID openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Serve HLS playlist or segment
// (GET /sessions/{sessionID}/hls/{filename})
func (_ Unimplemented) ServeHLS(w http.ResponseWriter, r *http.Request, sessionID openapi_types.UUID, filename string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List active streams
// (GET /streams)
func (_ Unimplemented) GetStreams(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Terminate a stream session
// (DELETE /streams/{id})
func (_ Unimplemented) DeleteStreamsId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get system configuration
// (GET /system/config)
func (_ Unimplemented) GetSystemConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update system configuration
// (PUT /system/config)
func (_ Unimplemented) PutSystemConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get system health
// (GET /system/health)
func (_ Unimplemented) GetSystemHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get minimal system health
// (GET /system/healthz)
func (_ Unimplemented) GetSystemHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger data refresh (EPG/Channels)
// (POST /system/refresh)
func (_ Unimplemented) PostSystemRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all timers
// (GET /timers)
func (_ Unimplemented) GetTimers(w http.ResponseWriter, r *http.Request, params GetTimersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a timer
// (POST /timers)
func (_ Unimplemented) AddTimer(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Preview conflicts
// (POST /timers/conflicts:preview)
func (_ Unimplemented) PreviewConflicts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete timer
// (DELETE /timers/{timerId})
func (_ Unimplemented) DeleteTimer(w http.ResponseWriter, r *http.Request, timerId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get timer
// (GET /timers/{timerId})
func (_ Unimplemented) GetTimer(w http.ResponseWriter, r *http.Request, timerId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Edit timer
// (PATCH /timers/{timerId})
func (_ Unimplemented) UpdateTimer(w http.ResponseWriter, r *http.Request, timerId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDvrCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetDvrCapabilities(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDvrCapabilities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDvrStatus operation middleware
func (siw *ServerInterfaceWrapper) GetDvrStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDvrStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEpg operation middleware
func (siw *ServerInterfaceWrapper) GetEpg(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEpgParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "bouquet" -------------

	err = runtime.BindQueryParameter("form", true, false, "bouquet", r.URL.Query(), &params.Bouquet)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bouquet", Err: err})
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEpg(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIntent operation middleware
func (siw *ServerInterfaceWrapper) CreateIntent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIntent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLogs operation middleware
func (siw *ServerInterfaceWrapper) GetLogs(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLogs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecordings operation middleware
func (siw *ServerInterfaceWrapper) GetRecordings(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRecordingsParams

	// ------------- Optional query parameter "root" -------------

	err = runtime.BindQueryParameter("form", true, false, "root", r.URL.Query(), &params.Root)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "root", Err: err})
		return
	}

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecordings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRecording operation middleware
func (siw *ServerInterfaceWrapper) DeleteRecording(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recordingId" -------------
	var recordingId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordingId", chi.URLParam(r, "recordingId"), &recordingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRecording(w, r, recordingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecordingPlaybackInfo operation middleware
func (siw *ServerInterfaceWrapper) GetRecordingPlaybackInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recordingId" -------------
	var recordingId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordingId", chi.URLParam(r, "recordingId"), &recordingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecordingPlaybackInfo(w, r, recordingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecordingHLSPlaylist operation middleware
func (siw *ServerInterfaceWrapper) GetRecordingHLSPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recordingId" -------------
	var recordingId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordingId", chi.URLParam(r, "recordingId"), &recordingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecordingHLSPlaylist(w, r, recordingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecordingsRecordingIdStatus operation middleware
func (siw *ServerInterfaceWrapper) GetRecordingsRecordingIdStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recordingId" -------------
	var recordingId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordingId", chi.URLParam(r, "recordingId"), &recordingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecordingsRecordingIdStatus(w, r, recordingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamRecordingDirect operation middleware
func (siw *ServerInterfaceWrapper) StreamRecordingDirect(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recordingId" -------------
	var recordingId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordingId", chi.URLParam(r, "recordingId"), &recordingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamRecordingDirect(w, r, recordingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecordingHLSTimeshift operation middleware
func (siw *ServerInterfaceWrapper) GetRecordingHLSTimeshift(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recordingId" -------------
	var recordingId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordingId", chi.URLParam(r, "recordingId"), &recordingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecordingHLSTimeshift(w, r, recordingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecordingHLSCustomSegment operation middleware
func (siw *ServerInterfaceWrapper) GetRecordingHLSCustomSegment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "recordingId" -------------
	var recordingId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordingId", chi.URLParam(r, "recordingId"), &recordingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordingId", Err: err})
		return
	}

	// ------------- Path parameter "segment" -------------
	var segment string

	err = runtime.BindStyledParameterWithOptions("simple", "segment", chi.URLParam(r, "segment"), &segment, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "segment", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecordingHLSCustomSegment(w, r, recordingId, segment)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSeriesRules operation middleware
func (siw *ServerInterfaceWrapper) GetSeriesRules(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSeriesRules(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSeriesRule operation middleware
func (siw *ServerInterfaceWrapper) CreateSeriesRule(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSeriesRule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunAllSeriesRules operation middleware
func (siw *ServerInterfaceWrapper) RunAllSeriesRules(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RunAllSeriesRulesParams

	// ------------- Optional query parameter "trigger" -------------

	err = runtime.BindQueryParameter("form", true, false, "trigger", r.URL.Query(), &params.Trigger)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trigger", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunAllSeriesRules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSeriesRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteSeriesRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSeriesRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSeriesRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateSeriesRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSeriesRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunSeriesRule operation middleware
func (siw *ServerInterfaceWrapper) RunSeriesRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RunSeriesRuleParams

	// ------------- Optional query parameter "trigger" -------------

	err = runtime.BindQueryParameter("form", true, false, "trigger", r.URL.Query(), &params.Trigger)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trigger", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunSeriesRule(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServices operation middleware
func (siw *ServerInterfaceWrapper) GetServices(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServicesParams

	// ------------- Optional query parameter "bouquet" -------------

	err = runtime.BindQueryParameter("form", true, false, "bouquet", r.URL.Query(), &params.Bouquet)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bouquet", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServicesBouquets operation middleware
func (siw *ServerInterfaceWrapper) GetServicesBouquets(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServicesBouquets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostServicesNowNext operation middleware
func (siw *ServerInterfaceWrapper) PostServicesNowNext(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostServicesNowNext(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostServicesIdToggle operation middleware
func (siw *ServerInterfaceWrapper) PostServicesIdToggle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostServicesIdToggle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSessionsParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSessionState operation middleware
func (siw *ServerInterfaceWrapper) GetSessionState(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionID" -------------
	var sessionID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sessionID", chi.URLParam(r, "sessionID"), &sessionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSessionState(w, r, sessionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServeHLS operation middleware
func (siw *ServerInterfaceWrapper) ServeHLS(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionID" -------------
	var sessionID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "sessionID", chi.URLParam(r, "sessionID"), &sessionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionID", Err: err})
		return
	}

	// ------------- Path parameter "filename" -------------
	var filename string

	err = runtime.BindStyledParameterWithOptions("simple", "filename", chi.URLParam(r, "filename"), &filename, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filename", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServeHLS(w, r, sessionID, filename)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStreams operation middleware
func (siw *ServerInterfaceWrapper) GetStreams(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStreams(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteStreamsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteStreamsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteStreamsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemConfig operation middleware
func (siw *ServerInterfaceWrapper) GetSystemConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutSystemConfig operation middleware
func (siw *ServerInterfaceWrapper) PutSystemConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:admin"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutSystemConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemHealth operation middleware
func (siw *ServerInterfaceWrapper) GetSystemHealth(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystemHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetSystemHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSystemRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostSystemRefresh(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSystemRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTimers operation middleware
func (siw *ServerInterfaceWrapper) GetTimers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTimersParams

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTimers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTimer operation middleware
func (siw *ServerInterfaceWrapper) AddTimer(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTimer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewConflicts operation middleware
func (siw *ServerInterfaceWrapper) PreviewConflicts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewConflicts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTimer operation middleware
func (siw *ServerInterfaceWrapper) DeleteTimer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "timerId" -------------
	var timerId string

	err = runtime.BindStyledParameterWithOptions("simple", "timerId", chi.URLParam(r, "timerId"), &timerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timerId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTimer(w, r, timerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTimer operation middleware
func (siw *ServerInterfaceWrapper) GetTimer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "timerId" -------------
	var timerId string

	err = runtime.BindStyledParameterWithOptions("simple", "timerId", chi.URLParam(r, "timerId"), &timerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timerId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTimer(w, r, timerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTimer operation middleware
func (siw *ServerInterfaceWrapper) UpdateTimer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "timerId" -------------
	var timerId string

	err = runtime.BindStyledParameterWithOptions("simple", "timerId", chi.URLParam(r, "timerId"), &timerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timerId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{"v3:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTimer(w, r, timerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/session", wrapper.CreateSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dvr/capabilities", wrapper.GetDvrCapabilities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dvr/status", wrapper.GetDvrStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/epg", wrapper.GetEpg)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/intents", wrapper.CreateIntent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/logs", wrapper.GetLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recordings", wrapper.GetRecordings)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/recordings/{recordingId}", wrapper.DeleteRecording)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recordings/{recordingId}/playback", wrapper.GetRecordingPlaybackInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recordings/{recordingId}/playlist.m3u8", wrapper.GetRecordingHLSPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recordings/{recordingId}/status", wrapper.GetRecordingsRecordingIdStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recordings/{recordingId}/stream.mp4", wrapper.StreamRecordingDirect)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recordings/{recordingId}/timeshift.m3u8", wrapper.GetRecordingHLSTimeshift)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/recordings/{recordingId}/{segment}", wrapper.GetRecordingHLSCustomSegment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/series-rules", wrapper.GetSeriesRules)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/series-rules", wrapper.CreateSeriesRule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/series-rules/run", wrapper.RunAllSeriesRules)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/series-rules/{id}", wrapper.DeleteSeriesRule)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/series-rules/{id}", wrapper.UpdateSeriesRule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/series-rules/{id}/run", wrapper.RunSeriesRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services", wrapper.GetServices)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/services/bouquets", wrapper.GetServicesBouquets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/services/now-next", wrapper.PostServicesNowNext)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/services/{id}/toggle", wrapper.PostServicesIdToggle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sessions", wrapper.ListSessions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sessions/{sessionID}", wrapper.GetSessionState)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sessions/{sessionID}/hls/{filename}", wrapper.ServeHLS)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/streams", wrapper.GetStreams)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/streams/{id}", wrapper.DeleteStreamsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/config", wrapper.GetSystemConfig)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/system/config", wrapper.PutSystemConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/health", wrapper.GetSystemHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/healthz", wrapper.GetSystemHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/system/refresh", wrapper.PostSystemRefresh)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/timers", wrapper.GetTimers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/timers", wrapper.AddTimer)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/timers/conflicts:preview", wrapper.PreviewConflicts)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/timers/{timerId}", wrapper.DeleteTimer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/timers/{timerId}", wrapper.GetTimer)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/timers/{timerId}", wrapper.UpdateTimer)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9a3PjuJF/BaXLB3sjP8b27u06dR80ljxWIss6yZ5NZsdRQWRLwpoEuAAoWzvr/34F",
	"gG+CFOXXbK4mqUo8IohHd6Pf3fzScpgfMApUitbpl5ZwluBj/Wdn1O9xzrj6O+AsAC4J6CcOc0H9vwvC",
	"4SSQhNHWaesSO0tCYY8DdvHMAwTqbaQHt1vwgP3Ag9Zp62bYubm+uBr3P/W6rXZLrgP1q5Cc0EXrsd1y",
	"QWLiifICV/oP7CHsuiT602FUwoPMLdCnK+wRF0l2BxTNGfexVBP7IAReWHZ+EfqYFvcdj87O3AnlEqgk",
	"DlZvIg6/hYSDazuFegZCTolbXm9snqF+V+0OuTALFwv1XnYtDr9N8cx5d3Rcnj6aX699+ksrAnG648zi",
	"t8nLbPYrOBoQnSA4Y3ROFmXUzlj4WwiGFogEX/9ROlz0A+YcrzXKsMRdwq1jIdDL/IXDvHXa+q+DlN4O",
	"ImI76I0+RPt5bLfmgGXI4dzDC7HpxfPs2Md2y2OLAazAs26EBUB/hln/fNOsV/HAdFMBcRjduJ2RHpW+",
	"tQIuNMa/WBBYwsp7A/oyTij2wXoiAXxFHMjiiFAJC+AVKygSd3joz7ZYJMBy2fAEZzFIJhLLUJQX8bCQ",
	"U2cJzp36V3QzTxX5wJ4kPtgukkjmAhr6itzZnboomjXdtpvtS2HkJlDrvBTJvyVZvzXl2mDYJRwcyfi6",
	"L8F/HfLprvgZDvCMeCSetih36NwjjrQ8CjisCNxnVpox5gGmhhc7QFbAO/eYg22IbTcCuHUTLniwwBLc",
	"EWcr4oKd6/mRiIxpljKqqDt5WbFrTPECXAsNt1siDALG1biGu1W3h1fsVoIdLOASWQUw7L7Hzt1H4GS+",
	"braHgkyKNtTOIC2BqU0mpZelfAa8trK4dguoEtiu/RCChdzJISG66a12KwC+F3HPhjykN/pQxdV8IgSh",
	"i6mzxJSCV7HXCj4WvdxwF+cFLpLfCKFCYiqvQ9qYyvtUApWRQmK7cZyDp7WdvlujkWXGxVoNUHdPsj2g",
	"LpIcO0a9KRE6ccEPmATqrP8B65oVMgPRHaz1Elju+UzIPUYdQAJ8rFQzYVsmwBwbxp7qjqPcSS1qaHYf",
	"nVTl1HOBNNRdAmjA2Zx4kZIZcHD0bT+VPITinANYYGeNsEew0OeJ3u130Y4LSqnbY9Rbt9E98Tw0A8TB",
	"ZytwEaFodbx/tGs9aTxHGZbXHFPhMJfQRbwU6ndzSufSE9P/PjoMrILY3JexkiI2jVbdfH0MITlgf19I",
	"zOU+6lGy8PERil5HHObAQWFsxyMrQIGH1zPs3CF11t393HbenR6evjs9Ofm+e3ry/fHpu9OzQ/WfU/Nf",
	"+yaFqCBW+x5ZgIi+A612qpCEIbEq9eYHNfEch540z5Kzqq1HV7vwc2a1hhd9wBY9Kvm6fCXnBDy3hpQN",
	"pZUm9Cr14oxZVD4wMWK9iapmO8aQ3Q/hQVYcBagFTTeUPCC1gpDYD9COAIdRV2SIPc9UuXzmHJJID+wq",
	"Sl6gqWHxkm29+dvqI1eoScpW3aCL5WD22G5Rdr/tK9Fdm3JzV+sPlh1cc6BKGZG1Qqr1Z5/Qvnn4rqhM",
	"2/cj6jcjAkaFRZtPdpD80QBwGlmPG/ZlJrRtqqh2l00MLOCGexUKshD3jLt2C08zjhHj0q5UhAJ4hept",
	"u445NX+LXVrnivh2n86ZRScq6L9LT0lLVxsRUz84sWq9HLCwmsuKouFO6Xp2VS+s2nUWf77xkqixNiSO",
	"OJt54HdT71ON8dGIuK6VCnwWvWZ1m+i1rOd9Ipc3GqBT4S5INNDmTDCVeRu4o3razjJJtZQNzmNwGFc6",
	"yPuQeG6VTo2lBD+Q0yIdzbFQzJezWSiklYgg9lmWnmjvQ8DZgoMQzR0Q8RtkpXgkdtc2zSoEROYIo8xg",
	"tKMl0JLM5a7WcjwiJCJC/61oeT9dLWu2wMIHKqcOC6msNCWUbTjFcjs3Sg6S/e6g12q3xjfDYX/4odVu",
	"nXf6A+2RHfc63X/Z9ZQcn9Yz1qLYLgRnsCB0GlLyMI0Es01Zi6ZA+rBamCMs0M2w/08UvbWfVdkIlT+c",
	"WOV7bmKboh9ybbg02Uw8Vqng0fC2QvwdZfe04X6U3l3pLvGALozDpNZFnezDvGncyEQoytJ69L7dJR0d",
	"w+qUfo8F/HAScm8PqLI9XJSMVybdzvj8DJ38cPJjG4U0wK4L7i6SDIUC9OoHyWhx8CX5u+8+5jX6y2t2",
	"f/Vr54fLLvthcPTO+/TBWw6Olnefzn6Ss+NPwafJT/7s6MfQvbjULpKHQQSQo8OTH7UWEf/w7gftXJLA",
	"1e7//Utn7xPe+/1w76fp3u1f/1JjwMRakdUYi11FNnNFQX8vsVIsunKlHll9Q6oVmVnirG0ucTIOXou4",
	"cULOFWepcMmlAzhj0n5VIidgUdeq21PecWjZVko4jefMMxjbnIzJJ0w3Vge36YE1CIxgVdBC7ercFqpa",
	"skCVhCQiGVLh/zIUPKxcM6fcZmazsvTQgwnFgVjajht5vsZWc6OdOPCK1kFW/yi61+s8exXQvYN1pSId",
	"cMI4kesagfozoS67b4qekCaanV3A5URztTSYecy5I3ShlcW+ffORndxgtjpbnq2AeziYpFKuwYR5p8/z",
	"eF5Iu+CQOCJW0PecSvm8DTQzsePnQBFLZzlOjJHmQaFaA2YDIKvRvyWQK4L22yiLdWTEQfJ1tSlWbS7Y",
	"9joJfR9bXUOB5u3iUqEixwey7v9o0MRR7KdikI8fzCTxsBFwxc0uqoIfPn7Ql1F88NgMe3o4vagOlRiF",
	"4YZywM6yBjB6zo6xa6o2awbFnGXDKA54wxBNCvVDJnckCOxDbDib6AiOgl+lFLDrV4kjv6xYSYY4KEJx",
	"JOKhZ6XIWITkJ+3itUBsju4B7tDO4f9MQuri9W6rnd5ZHz8QX1k8P2jt0fx92N5OBCX+3pzZXZJISvu6",
	"ot66MM4qofIHmQDmzhJJ4D5iHHFYwIOJoqyAKutH2sGiTNpxSDtb3O3olUnRGVAekd7NWuUpHVmQswnU",
	"Ditdt9P7ROgWLGpl75mH6OLi8nJP/U8zn3NKouOQjiGInGfP9eZkJb7Vl2NE21YTJvLQNmFk4l02FdXa",
	"8bHV8kZSWNaeE0rEEtxt6Erd3AoBxkNa8URkVMr6zWbUz9QD0pHPySMRoeOAEC0dHpQEe8p+x8SrjMk/",
	"4T5IThaLihwBQ97nnPkNMWxeuGaNhtdfjapkmP+/PLzMtJ/LjbPOiPaTTI4XYH9ZIy4+bXq0zC5u7fSg",
	"UyAskbkauC04CwMrRVcYZh5bsGlYEf+odIXR0J9V3JxaT86kRJxpwJfQBdqBB8mx0q7QnDMfXR7foJvx",
	"YLepdNEBZmMtW+WKhAfZxRJvlW1QWqeUeVH21hj9ryNvKHloyEGUaO9orrfFS5mUhtI2U4un6DJVv+vk",
	"37+h8XTQ60x60/c3k38hHzAVyMEBdohcIw5qKsIo2qEMyZACR3iFiacIcLeNKJMII7EWEnyk9Yn9TJx9",
	"PB1eDbUbe3oz/Mfw6ueh/vt9pzsd9/73pje51v8eXl1Pz69uhtq7ndmM/uf1zbA3ve5f9q5urjPPe/8c",
	"9cfGH26GpP7xaX/4sTPud4bX04/9q0Hnun9l1j0/vxz1Pkwn153xdXb8aHx11ptMpr1hN/6lc/aPzofe",
	"ODvqrDM86w2SNbqD/LbOBv3e8Ho6ub4a1UTPutUxpQ0maC51YmMqRBJPKF4+PQnyyBycteMB0gP3kQ4q",
	"oEWIOaYSQCCcxEHQxWAS3U+0kwRK/oqwRB5gIRGjgKKwSPszxZL5xMGet0ZBOPO0orK7j0bj/mV/+CGi",
	"r/NzP4AFIgLxkFJ17WehNNniVAdhFF2tQabBmM80Q1fD3s+tdkvj0QRHotmT6Ei71R13+lHkRKFklPlT",
	"YzBBbIpWG9Y0xZtsndKzUAvpbW54Lceq8jRvZjWxLjqpipB0P45jcWUiGJrn6vyeiKxEOxMzyUVK5h7D",
	"Mj1LxPYVsyIr6LkLqFz1zPirzTrgLgAFTJBCfCZKM0r89pvX9a3lDXG8G6nH+nhymZwuy5MG/Y+aI/XO",
	"rsZdRRU2tMdZT1G8vWKpm/EgWUldkvhy5M4RclKTCFbhw/nGtf9zuLbJfOhRt/IiDLAEIVE81HYNmpF+",
	"PMNEaaeVy/Uw98hLLfhNJv3pZFIidy6rSkvy+Voxjto1OQETDcsIFdV2Z6U14HgEqJySrQyPF0mUwI4k",
	"KzWUuF7TbPGJ5nwXgD0Tai05txvUjkQeuoyPedNLxfqb6qxzFxYcu9pUrCqkUWSgYJRNi2hgLGxX86Qd",
	"7c8LoCVmUHMUb8oIaR4pqiTXGGWTmJq2SuOqD91u5ppFElYE4obGNZCE23Vthh94YMpRXCJi70FIdT6L",
	"XV+tCVQlfGOLlOFSzYjhI+kB4wCgQUsE8jpOk0+7K9NWNuDaKIVv+8BqlWMqcwvNOwruYeARRx0mMgam",
	"HvGJrEWDPfkuf7KNoBmZkqnKvN5UDY6T3R1lP/AVjvhhfJbCz/lqq1u7ahowYdxLmxMo9f2Od1k8ejJV",
	"8+NWmkGYTqJ7Yvd7vUIGqAgXCxCyFDfI7+yOGIYUA5yDGzowDRRP0fdYJxlOk2oD/a98fnrGrcZkRaVe",
	"BMr3WzDf+J1eQ45pLV2rS7rOIiWLgWp058ilHAWfS+C9FVCZJ+34r5Sq01+ExNSdrbXYhCD9F2VyaS/d",
	"2jZpYZM4ah6IbC66ypVXpYV/DYVUtmhu5Tn2hHXpmhJQTacdBfoJOJtDg9EL72HOODR6o1Yg2usLKmVL",
	"JWkNiI2itis4SATKE0sN9Psjk59SQeKvRHrPobVtSKMZOWxmLJoqnJATuVYcxDfAeQ+YA++ERi2f6X+d",
	"xwf4+8/KZteo0kfVT9MDLaUMWo+POs3e1DwUagRHfe2teVgcLdBOXPcmGRp58HDwd/C89ZxQNOLsYb27",
	"/5l+pt99NyAOUAHffXeKRsxbq62gIaMO833gDsEeikagd/uH+4f7n+lZ+ihUKom2J6PQG7j7aAKAOGiD",
	"nPE1cpkTKiPVpAubdhM6R8oYl1FuUUvvuTPqtzIafOtYLRkXoOOARD8dt0xZtwboAQ7l8kBk7DomLBVZ",
	"vQdl4S1AaF+WwULaoANhpHEF6ELK4Ip669ixhhzG7gi0kaZEZTNTrWekZYM7F4PJLroncslCGU1JKLoZ",
	"D/Zbeuc88Wy2jHCIjVB154wyoE9ydHhS7TuIrAwFjJPDd7aKMwUHxsnvalCG9lqnv+Sp7pfW6viUA3Zb",
	"t4+3mahytLnCwRWKdK3vLy21QOtWzX3grviBUyiVX5jWEfkDfwBZrKovnfowiVsZoYgDo5ASRg9+jdyE",
	"hn1tTPUtLKXvSsFlm3+ePf8HkKj7cYyc/G7j47srnjl9atfWnDsyg1/xxMUsXcuJc5UMZozt1Lw4zHby",
	"yHFQdeResGhFtc6mPlnRXoGek2qKqDQypOQBZeojleho/RYCX8fy8LQ158yPGSO2c9/SfafutqtItuUa",
	"58STwNFsjaLCfhTZhrbZ09r/0hKpnlC9gjApAfGkthV+q5379plUuEnpKLZ9EE6da6NSg6ooGc1U2m5V",
	"QLtZ2S9K7dL96Y0+IBdLbLk3yaP0rqgbYu6KqeoWWZFkEwb9uPg76pn0npkCrxdhD/nuCo95NU+p8I8l",
	"qjh6BlVsDuRt70/POw+x40Bg/EWJ/SCnHJQ0buQaLePXwAglM2sJ+3IcOuliZl3aNArjMYLU0j+9ydID",
	"wALQLBRrtFOOqv0NUZYqAkb1UGxzCdiN2ryMQfL1nlacbVqLCX1Khu4xkWimVWekU7frmaza6feHx28C",
	"g4/HOvjBmae0OQoopEkMsYEOdc+JhColykRuDA9AO6aGUGcBsSAG7G6GbayOI67hsUWtVjFQz5/JyhsZ",
	"ikkDiDLTtKkYOgzOFgio5IlqVQs+7PqEFsGnuCpPZjPTHOQLtKogM05HbdBBxoyp6Z24XUyFPNVVaFuJ",
	"67Fmfso4wHJZMWv06PUEdbNCs9gLWacwCuSRyOWZYug9Z/cCEM9CO6bizI+3BczlazLznaEKqRz6d2On",
	"pUrpimCUtDlAjMaPtae3bGiZScaZUEMtRTyl9lTn7uUKAfdzBa4R+iN8xzSVAqFVlMVZovgzFKxaKPGk",
	"tjYZTCgnFaBV0i5+I8mQNO8cW1waOlcQuUBJPHPtHiiTaM5Cqsd+b9vFuU6wVpLJ7DfdzlNZvqE1hFE2",
	"srX1lTiIHQqNeFyu+UWJuJ9BeG/JjXKHsDCiJA1JSI4lLNZI+71SKnh1DcFKWCUzICjt07iUnk8POtfK",
	"Pw5/bEQUF4PJKHrpG8N7GYZXR+wr6u6rf8O+H8AiSi+v0RZyLz/sqZduxoP6l0oUeTGYoATJX8VUScnk",
	"q9/EtzMV8svrLiz6kn+86loYwserbi5d8kX4wWaPY6q4pbfUTXyQ/5kywtqtx4Ig/TjxcH7te/FosWmi",
	"x7PcRjdgXHft84OTSqybrLYESKbXxVdG9oq4wA6iXacTJd6eGaFYW0Qbmd1HNVNkS2+n/OUQYICUwQEW",
	"6HJ0gnYMuNR13X3SlUz6K20lo6/jt74J6W9C+puQfn0hnVxTC2NOnr28wP4SpWc/NmUMZ6GQzJ+Yt74x",
	"h6cwh7ZV1okEpNXbT5fZ/+7z5/0dKf7wg5M//BPxh+PPV7vPZ0XMkSD3Imm2pWhsR1L1cnR0/dR3iWD7",
	"MSSeOIUfHD3j3ecrBJfgEoziG/KNs75VtMjCWS28VJesGNxsw0BNU/49Hnr1iSRp84C3iYBkWs00iIEM",
	"lNhgc2SOkQeOfoY93beAgMh6QKPTxMCJP1Dw2K4NGme29jqB4+zZm0SN373ayoX0nTgN6lnROYwo3CfI",
	"iLpFFDFQJM0DHtLqYP44pB3Py5OozQgr5pxE7TmykihNCvYxDXVXkJe2uLek/7SPzVYXgeo8QC7FU9E1",
	"Dqm+NlEWaBZjAhHfV9JAgrduhL4vpBh3soWMCjdrU/Sjm4152IzT0IOiXfqMCMMGkm1i95Otzf0gtNC7",
	"6d/yhnwoahjTiBsdvhE3MntqEvHK5He8GpWY3SBMETwQIXUq35YsTt2RjXwuh/QXJ7j2n4pRbs0fLbpT",
	"wgdfGf+aWyIRgEPmxMniviGvTL6iUKOBmTEbbNMXT4x8K3mnmxFtIeMSoFXre/o52om/zbTbykH7IPvx",
	"t01gfx+PfQtoxF8D3AIayVkqoDFL958hwehbG3mwUHa/F3+rxM6IRkwkgIm+ovFKMqjw/ZE3lkDFD45Y",
	"4D9k9wcKWDofNUrAQkHaQ7y5fCqZdDQ7tbHpvCLtb8amFiuSLRZR186NCO2712b062g0T6WSxj3K7Hmn",
	"jYimlC4vQ4HCrKJxUt1y7NkyxIA96a+XKN7S6F4aqSJpM2llWOq6T+JBGwTFCC8INWl4bD4XWgrYZETy",
	"0CL8D+t78pWz9DKL6kpntOPjB/Tu8PCwqjIgLoi2rP7u8LCd9gdUk2S2886ynZfNww+Ss9iysSs/4GEO",
	"ZH0UgdqeaM8k9pp26s0SSkP5m+1s96Rc/ZjuDJO6J3KJUgghHyQ2mfz/MTnG1iTZjHoRHXdHjzM9pmxZ",
	"xfHAgy9xAn73sV7j0KNM84hXVaHzrcGqURqzoLd3+cZp8G/r8I2PvQ1HtxX1KSEuciAskEcTCZsQTa2g",
	"3VDO8XhbRYkHS08cfIk/S1NNmErKwcVg0nrdCPCfJNLy/GjJxWASd3d6tovinORN1ISDvii7s1Gwxno+",
	"Oss4SkN6X4ma7ZHG5NtKzUKN//4F7/3e2ft0uPfTdH/v9q+fP+/v+Mfhj39IoSOPfnBiDzzqq6QjifWW",
	"YzTkTcznXIOtBmZjR/e1SoTY86RhNFd03scMfJo6fs1oHeR+HZujaam3BO4rlaVW399eOtj1/XgthOOa",
	"pbiU3sBQ9xE7cJIvNlZSmh4YfdnxFTWGThAkX4kvR4f0k6hX6HNKkKLGkU5+vgpX+Cgsn/7lvRBm8tfz",
	"gudtBw6mP3i6RlMjtwYjeTO2RhiV4L6hkkPgFRRfehryIx+6Hf+ZC7FMOuvVX4ioA99rqtDZdWxKgH5S",
	"XfsfHXUZT1A84+9ND/n7c09p71AXtfspfPLX1lWw0QcjrR8FbQS1lJhK7EIb/NirgSWHOQex3OD90mPH",
	"0VB7ZXYxL0OPRVGfyUxKiH0c9kxWHKHJh0KfLDlMQEbXv6PoeGinN/pwcJZ3dZvP/NRRkfnaUbOAeWzD",
	"2KJA2S6DDcNKmztLvGYEKe3qVONVj+BX4VOXMexiNTj6oTqDpOO6pgnU68gpa8+8N80giVpclSGqH+Q7",
	"6bxc+lTh882W5btxo0WDNL2Bo6M33EDcCFDZT1rQGqkM8Vd4vj98y92M4y+dEuowKogwpfIr4GQerYnM",
	"13B2n53uIyOCL12SlEEdJL39TgPTqbGGWZsBZ0k3wNe8SvZumW8chartZGkr3TRDEAeheHOeecUPnQz8",
	"6jDzJerL2sCKiznbZgsu7fX6wmbcppSg4QtlA1XSdLte0L4hdA7fiqfHn92sgrkZVVfDWwPNAEtnWZUB",
	"9QYgfSXGkmvi+DXYSTU6N4U7S+j8eqLcMDj9CXTOfAQukV9PsGeEeIWsVQIVHaAx8zzda+CJLKjnkpor",
	"s5WfF/iqIjbMmRuab3yYvpDadd86wAE5WB23Hm8f/y8AAP//z6O5dTyWAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
