// Code generated by gen-native-contract from backend/api/openapi.yaml; DO NOT EDIT.
//
// Copyright (c) 2026 ManuGH
// Licensed under the PolyForm Noncommercial License 1.0.0
// Since v2.0.0, this software is restricted to non-commercial use only.

package io.github.manugh.xg2g.android.contract

import java.time.Instant
import org.json.JSONArray
import org.json.JSONObject

/**
 * Raised when a response does not match the published contract.
 *
 * A missing required field is a contract violation, not a value to paper over
 * with a default. Reporting which field failed is what turns a silent decode
 * into a diagnosable one.
 */
class Xg2gContractException(message: String) : RuntimeException(message)

private fun JSONObject.requireField(name: String, owner: String): Any {
    if (isNull(name)) {
        throw Xg2gContractException("$owner: missing required field '$name'")
    }
    return get(name)
}

private fun requireString(value: Any, owner: String, name: String): String =
    value as? String ?: throw Xg2gContractException("$owner: field '$name' is not a string")

private fun requireInt(value: Any, owner: String, name: String): Int =
    (value as? Number)?.toInt() ?: throw Xg2gContractException("$owner: field '$name' is not a number")

private fun requireLong(value: Any, owner: String, name: String): Long =
    (value as? Number)?.toLong() ?: throw Xg2gContractException("$owner: field '$name' is not a number")

private fun requireDouble(value: Any, owner: String, name: String): Double =
    (value as? Number)?.toDouble() ?: throw Xg2gContractException("$owner: field '$name' is not a number")

private fun requireBoolean(value: Any, owner: String, name: String): Boolean =
    value as? Boolean ?: throw Xg2gContractException("$owner: field '$name' is not a boolean")

private fun requireObject(value: Any, owner: String, name: String): JSONObject =
    value as? JSONObject ?: throw Xg2gContractException("$owner: field '$name' is not an object")

private fun requireArray(value: Any, owner: String, name: String): JSONArray =
    value as? JSONArray ?: throw Xg2gContractException("$owner: field '$name' is not an array")

// RFC 3339, matching `format: date-time` in the spec. Instant.parse accepts both
// the fractional and non-fractional forms Go's time.Time emits.
private fun requireInstant(value: Any, owner: String, name: String): Instant {
    val text = requireString(value, owner, name)
    return runCatching { Instant.parse(text) }.getOrElse {
        throw Xg2gContractException("$owner: field '$name' is not an RFC 3339 timestamp: $text")
    }
}

private fun JSONObject.optionalField(name: String): Any? = if (isNull(name)) null else get(name)

enum class DeviceAuthDeviceType(val wireValue: String) {
    ANDROID_PHONE("android_phone"),
    ANDROID_TABLET("android_tablet"),
    ANDROID_TV("android_tv"),
    IOS_PHONE("ios_phone"),
    IOS_TABLET("ios_tablet"),
    APPLE_TV("apple_tv"),
    BROWSER("browser"),
    UNKNOWN("unknown");

    companion object {
        fun fromWire(value: String, owner: String = "DeviceAuthDeviceType"): DeviceAuthDeviceType =
            entries.firstOrNull { it.wireValue == value }
                ?: throw Xg2gContractException("$owner: '$value' is not a known DeviceAuthDeviceType")
    }
}

enum class ECPublicKeyJWKCrv(val wireValue: String) {
    P_256("P-256");

    companion object {
        fun fromWire(value: String, owner: String = "ECPublicKeyJWKCrv"): ECPublicKeyJWKCrv =
            entries.firstOrNull { it.wireValue == value }
                ?: throw Xg2gContractException("$owner: '$value' is not a known ECPublicKeyJWKCrv")
    }
}

enum class ECPublicKeyJWKKty(val wireValue: String) {
    EC("EC");

    companion object {
        fun fromWire(value: String, owner: String = "ECPublicKeyJWKKty"): ECPublicKeyJWKKty =
            entries.firstOrNull { it.wireValue == value }
                ?: throw Xg2gContractException("$owner: '$value' is not a known ECPublicKeyJWKKty")
    }
}

enum class PairingStatus(val wireValue: String) {
    PENDING("pending"),
    APPROVED("approved"),
    EXPIRED("expired"),
    CONSUMED("consumed"),
    REVOKED("revoked");

    companion object {
        fun fromWire(value: String, owner: String = "PairingStatus"): PairingStatus =
            entries.firstOrNull { it.wireValue == value }
                ?: throw Xg2gContractException("$owner: '$value' is not a known PairingStatus")
    }
}

enum class PublishedEndpointKind(val wireValue: String) {
    PUBLIC_HTTPS("public_https"),
    LOCAL_HTTPS("local_https"),
    LOCAL_HTTP("local_http");

    companion object {
        fun fromWire(value: String, owner: String = "PublishedEndpointKind"): PublishedEndpointKind =
            entries.firstOrNull { it.wireValue == value }
                ?: throw Xg2gContractException("$owner: '$value' is not a known PublishedEndpointKind")
    }
}

enum class PublishedEndpointSource(val wireValue: String) {
    CONFIG("config"),
    ENV("env"),
    OPERATOR("operator");

    companion object {
        fun fromWire(value: String, owner: String = "PublishedEndpointSource"): PublishedEndpointSource =
            entries.firstOrNull { it.wireValue == value }
                ?: throw Xg2gContractException("$owner: '$value' is not a known PublishedEndpointSource")
    }
}

enum class PublishedEndpointTLSMode(val wireValue: String) {
    REQUIRED("required"),
    PROHIBITED("prohibited");

    companion object {
        fun fromWire(value: String, owner: String = "PublishedEndpointTLSMode"): PublishedEndpointTLSMode =
            entries.firstOrNull { it.wireValue == value }
                ?: throw Xg2gContractException("$owner: '$value' is not a known PublishedEndpointTLSMode")
    }
}

data class ApprovePairingRequest(
    val approvedPolicyProfile: String? = null,
    val ownerId: String? = null
) {
    companion object {
        fun fromJson(json: JSONObject, owner: String = "ApprovePairingRequest"): ApprovePairingRequest = ApprovePairingRequest(
            approvedPolicyProfile = json.optionalField("approvedPolicyProfile")?.let { requireString(it, owner, "approvedPolicyProfile") },
            ownerId = json.optionalField("ownerId")?.let { requireString(it, owner, "ownerId") }
        )
    }

    fun toJson(): JSONObject = JSONObject().apply {
        approvedPolicyProfile?.let { put("approvedPolicyProfile", it) }
        ownerId?.let { put("ownerId", it) }
    }
}

data class ApprovePairingResponse(
    val approvedAt: Instant? = null,
    val approvedPolicyProfile: String? = null,
    val expiresAt: Instant,
    val ownerId: String,
    val pairingId: String,
    val status: PairingStatus
) {
    companion object {
        fun fromJson(json: JSONObject, owner: String = "ApprovePairingResponse"): ApprovePairingResponse = ApprovePairingResponse(
            approvedAt = json.optionalField("approvedAt")?.let { requireInstant(it, owner, "approvedAt") },
            approvedPolicyProfile = json.optionalField("approvedPolicyProfile")?.let { requireString(it, owner, "approvedPolicyProfile") },
            expiresAt = requireInstant(json.requireField("expiresAt", owner), owner, "expiresAt"),
            ownerId = requireString(json.requireField("ownerId", owner), owner, "ownerId"),
            pairingId = requireString(json.requireField("pairingId", owner), owner, "pairingId"),
            status = PairingStatus.fromWire(requireString(json.requireField("status", owner), owner, "status"), owner)
        )
    }

    fun toJson(): JSONObject = JSONObject().apply {
        approvedAt?.let { put("approvedAt", it.toString()) }
        approvedPolicyProfile?.let { put("approvedPolicyProfile", it) }
        put("expiresAt", expiresAt.toString())
        put("ownerId", ownerId)
        put("pairingId", pairingId)
        put("status", status.wireValue)
    }
}

/**
 * A freshly issued, DPoP-bound device grant.
 *
 * The field names are snake_case here and camelCase in
 * ExchangePairingResponse. That is the wire as it stands, documented
 * rather than quietly corrected: aligning the two casings is a breaking
 * change for any device already speaking this endpoint.
 */
data class DeviceGrantResponse(
    val accessToken: String,
    val deviceId: String,
    /**
     * Access-token lifetime in seconds, counted from this response.
     */
    val expiresIn: Int,
    /**
     * Replaces the presented token. Presenting a superseded value is treated as replay and revokes the whole refresh family.
     */
    val refreshToken: String,
    val scope: String,
    /**
     * Always "DPoP"; the token is sender-constrained to the device key.
     */
    val tokenType: String
) {
    companion object {
        fun fromJson(json: JSONObject, owner: String = "DeviceGrantResponse"): DeviceGrantResponse = DeviceGrantResponse(
            accessToken = requireString(json.requireField("access_token", owner), owner, "access_token"),
            deviceId = requireString(json.requireField("device_id", owner), owner, "device_id"),
            expiresIn = requireInt(json.requireField("expires_in", owner), owner, "expires_in"),
            refreshToken = requireString(json.requireField("refresh_token", owner), owner, "refresh_token"),
            scope = requireString(json.requireField("scope", owner), owner, "scope"),
            tokenType = requireString(json.requireField("token_type", owner), owner, "token_type")
        )
    }

    fun toJson(): JSONObject = JSONObject().apply {
        put("access_token", accessToken)
        put("device_id", deviceId)
        put("expires_in", expiresIn)
        put("refresh_token", refreshToken)
        put("scope", scope)
        put("token_type", tokenType)
    }
}

data class DeviceRefreshRequest(
    /**
     * The rotating refresh token most recently issued to this device, either by the pairing exchange or by a previous refresh.
     */
    val refreshToken: String
) {
    companion object {
        fun fromJson(json: JSONObject, owner: String = "DeviceRefreshRequest"): DeviceRefreshRequest = DeviceRefreshRequest(
            refreshToken = requireString(json.requireField("refresh_token", owner), owner, "refresh_token")
        )
    }

    fun toJson(): JSONObject = JSONObject().apply {
        put("refresh_token", refreshToken)
    }
}

/**
 * P-256 public key in JWK form. The server computes the RFC 7638
 * thumbprint itself; a client-supplied thumbprint is never trusted.
 *
 * additionalProperties is false so private key parameters (notably "d")
 * are refused by the contract, not merely by the decoder.
 */
data class ECPublicKeyJWK(
    val crv: ECPublicKeyJWKCrv,
    val kty: ECPublicKeyJWKKty,
    /**
     * Unpadded base64url; must decode to exactly 32 bytes.
     */
    val x: String,
    /**
     * Unpadded base64url; must decode to exactly 32 bytes.
     */
    val y: String
) {
    companion object {
        fun fromJson(json: JSONObject, owner: String = "ECPublicKeyJWK"): ECPublicKeyJWK = ECPublicKeyJWK(
            crv = ECPublicKeyJWKCrv.fromWire(requireString(json.requireField("crv", owner), owner, "crv"), owner),
            kty = ECPublicKeyJWKKty.fromWire(requireString(json.requireField("kty", owner), owner, "kty"), owner),
            x = requireString(json.requireField("x", owner), owner, "x"),
            y = requireString(json.requireField("y", owner), owner, "y")
        )
    }

    fun toJson(): JSONObject = JSONObject().apply {
        put("crv", crv.wireValue)
        put("kty", kty.wireValue)
        put("x", x)
        put("y", y)
    }
}

data class ExchangePairingResponse(
    val accessToken: String,
    val deviceId: String,
    val endpoints: List<PublishedEndpoint>,
    /**
     * Access-token lifetime in seconds, from the moment of the response.
     */
    val expiresIn: Int,
    val pairingId: String,
    val policyVersion: String,
    /**
     * Rotates on every refresh. Presenting a superseded value is treated as replay and revokes the whole family.
     */
    val refreshToken: String,
    val scope: String,
    /**
     * Always "DPoP"; the token is sender-constrained to the enrolled device key.
     */
    val tokenType: String
) {
    companion object {
        fun fromJson(json: JSONObject, owner: String = "ExchangePairingResponse"): ExchangePairingResponse = ExchangePairingResponse(
            accessToken = requireString(json.requireField("accessToken", owner), owner, "accessToken"),
            deviceId = requireString(json.requireField("deviceId", owner), owner, "deviceId"),
            endpoints = requireArray(json.requireField("endpoints", owner), owner, "endpoints").let { array -> (0 until array.length()).map { index -> PublishedEndpoint.fromJson(requireObject(array.get(index), owner, "endpoints"), owner) } },
            expiresIn = requireInt(json.requireField("expiresIn", owner), owner, "expiresIn"),
            pairingId = requireString(json.requireField("pairingId", owner), owner, "pairingId"),
            policyVersion = requireString(json.requireField("policyVersion", owner), owner, "policyVersion"),
            refreshToken = requireString(json.requireField("refreshToken", owner), owner, "refreshToken"),
            scope = requireString(json.requireField("scope", owner), owner, "scope"),
            tokenType = requireString(json.requireField("tokenType", owner), owner, "tokenType")
        )
    }

    fun toJson(): JSONObject = JSONObject().apply {
        put("accessToken", accessToken)
        put("deviceId", deviceId)
        put("endpoints", JSONArray(endpoints.map { element -> element.toJson() }))
        put("expiresIn", expiresIn)
        put("pairingId", pairingId)
        put("policyVersion", policyVersion)
        put("refreshToken", refreshToken)
        put("scope", scope)
        put("tokenType", tokenType)
    }
}

data class PairingSecretRequest(
    /**
     * P-256 public key in JWK form. The server computes the RFC 7638
     * thumbprint itself; a client-supplied thumbprint is never trusted.
     *
     * additionalProperties is false so private key parameters (notably "d")
     * are refused by the contract, not merely by the decoder.
     */
    val deviceJwk: ECPublicKeyJWK,
    val pairingSecret: String
) {
    companion object {
        fun fromJson(json: JSONObject, owner: String = "PairingSecretRequest"): PairingSecretRequest = PairingSecretRequest(
            deviceJwk = ECPublicKeyJWK.fromJson(requireObject(json.requireField("deviceJwk", owner), owner, "deviceJwk"), owner),
            pairingSecret = requireString(json.requireField("pairingSecret", owner), owner, "pairingSecret")
        )
    }

    fun toJson(): JSONObject = JSONObject().apply {
        put("deviceJwk", deviceJwk.toJson())
        put("pairingSecret", pairingSecret)
    }
}

data class PairingStatusResponse(
    val approvedAt: Instant? = null,
    val approvedPolicyProfile: String? = null,
    val consumedAt: Instant? = null,
    val deviceName: String,
    val deviceType: DeviceAuthDeviceType,
    val expiresAt: Instant,
    val pairingId: String,
    val requestedPolicyProfile: String? = null,
    val status: PairingStatus,
    val userCode: String
) {
    companion object {
        fun fromJson(json: JSONObject, owner: String = "PairingStatusResponse"): PairingStatusResponse = PairingStatusResponse(
            approvedAt = json.optionalField("approvedAt")?.let { requireInstant(it, owner, "approvedAt") },
            approvedPolicyProfile = json.optionalField("approvedPolicyProfile")?.let { requireString(it, owner, "approvedPolicyProfile") },
            consumedAt = json.optionalField("consumedAt")?.let { requireInstant(it, owner, "consumedAt") },
            deviceName = requireString(json.requireField("deviceName", owner), owner, "deviceName"),
            deviceType = DeviceAuthDeviceType.fromWire(requireString(json.requireField("deviceType", owner), owner, "deviceType"), owner),
            expiresAt = requireInstant(json.requireField("expiresAt", owner), owner, "expiresAt"),
            pairingId = requireString(json.requireField("pairingId", owner), owner, "pairingId"),
            requestedPolicyProfile = json.optionalField("requestedPolicyProfile")?.let { requireString(it, owner, "requestedPolicyProfile") },
            status = PairingStatus.fromWire(requireString(json.requireField("status", owner), owner, "status"), owner),
            userCode = requireString(json.requireField("userCode", owner), owner, "userCode")
        )
    }

    fun toJson(): JSONObject = JSONObject().apply {
        approvedAt?.let { put("approvedAt", it.toString()) }
        approvedPolicyProfile?.let { put("approvedPolicyProfile", it) }
        consumedAt?.let { put("consumedAt", it.toString()) }
        put("deviceName", deviceName)
        put("deviceType", deviceType.wireValue)
        put("expiresAt", expiresAt.toString())
        put("pairingId", pairingId)
        requestedPolicyProfile?.let { put("requestedPolicyProfile", it) }
        put("status", status.wireValue)
        put("userCode", userCode)
    }
}

data class PublishedEndpoint(
    val advertiseReason: String,
    val allowNative: Boolean,
    val allowPairing: Boolean,
    val allowStreaming: Boolean,
    val allowWeb: Boolean,
    val kind: PublishedEndpointKind,
    val priority: Int,
    val source: PublishedEndpointSource,
    val tlsMode: PublishedEndpointTLSMode,
    val url: String
) {
    companion object {
        fun fromJson(json: JSONObject, owner: String = "PublishedEndpoint"): PublishedEndpoint = PublishedEndpoint(
            advertiseReason = requireString(json.requireField("advertiseReason", owner), owner, "advertiseReason"),
            allowNative = requireBoolean(json.requireField("allowNative", owner), owner, "allowNative"),
            allowPairing = requireBoolean(json.requireField("allowPairing", owner), owner, "allowPairing"),
            allowStreaming = requireBoolean(json.requireField("allowStreaming", owner), owner, "allowStreaming"),
            allowWeb = requireBoolean(json.requireField("allowWeb", owner), owner, "allowWeb"),
            kind = PublishedEndpointKind.fromWire(requireString(json.requireField("kind", owner), owner, "kind"), owner),
            priority = requireInt(json.requireField("priority", owner), owner, "priority"),
            source = PublishedEndpointSource.fromWire(requireString(json.requireField("source", owner), owner, "source"), owner),
            tlsMode = PublishedEndpointTLSMode.fromWire(requireString(json.requireField("tlsMode", owner), owner, "tlsMode"), owner),
            url = requireString(json.requireField("url", owner), owner, "url")
        )
    }

    fun toJson(): JSONObject = JSONObject().apply {
        put("advertiseReason", advertiseReason)
        put("allowNative", allowNative)
        put("allowPairing", allowPairing)
        put("allowStreaming", allowStreaming)
        put("allowWeb", allowWeb)
        put("kind", kind.wireValue)
        put("priority", priority)
        put("source", source.wireValue)
        put("tlsMode", tlsMode.wireValue)
        put("url", url)
    }
}

data class StartPairingRequest(
    val deviceName: String? = null,
    val deviceType: DeviceAuthDeviceType? = null,
    val requestedPolicyProfile: String? = null
) {
    companion object {
        fun fromJson(json: JSONObject, owner: String = "StartPairingRequest"): StartPairingRequest = StartPairingRequest(
            deviceName = json.optionalField("deviceName")?.let { requireString(it, owner, "deviceName") },
            deviceType = json.optionalField("deviceType")?.let { DeviceAuthDeviceType.fromWire(requireString(it, owner, "deviceType"), owner) },
            requestedPolicyProfile = json.optionalField("requestedPolicyProfile")?.let { requireString(it, owner, "requestedPolicyProfile") }
        )
    }

    fun toJson(): JSONObject = JSONObject().apply {
        deviceName?.let { put("deviceName", it) }
        deviceType?.let { put("deviceType", it.wireValue) }
        requestedPolicyProfile?.let { put("requestedPolicyProfile", it) }
    }
}

data class StartPairingResponse(
    val expiresAt: Instant,
    val pairingId: String,
    val pairingSecret: String,
    val qrPayload: String,
    val userCode: String
) {
    companion object {
        fun fromJson(json: JSONObject, owner: String = "StartPairingResponse"): StartPairingResponse = StartPairingResponse(
            expiresAt = requireInstant(json.requireField("expiresAt", owner), owner, "expiresAt"),
            pairingId = requireString(json.requireField("pairingId", owner), owner, "pairingId"),
            pairingSecret = requireString(json.requireField("pairingSecret", owner), owner, "pairingSecret"),
            qrPayload = requireString(json.requireField("qrPayload", owner), owner, "qrPayload"),
            userCode = requireString(json.requireField("userCode", owner), owner, "userCode")
        )
    }

    fun toJson(): JSONObject = JSONObject().apply {
        put("expiresAt", expiresAt.toString())
        put("pairingId", pairingId)
        put("pairingSecret", pairingSecret)
        put("qrPayload", qrPayload)
        put("userCode", userCode)
    }
}

