// Copyright (c) 2025 ManuGH
// Licensed under the PolyForm Noncommercial License 1.0.0
// Since v2.0.0, this software is restricted to non-commercial use only.

// Package v3 implements the experimental Control Plane and Orchestration Layer.
//
// Overview:
// The v3 architecture introduces a stateful, event-driven model for managing streams,
// replacing the purely stateless proxy model of v2. It is designed to handle complex
// transcoding scenarios, resource contention (tuner slots), and session lifecycle management.
//
// Core Components:
//
//  1. Intent-Based API (/api/v3/intents):
//     Clients request a "Stream Start" or "Stream Stop" intent. The API validates the request,
//     checks idempotency, and publishes an event to the internal Event Bus.
//     It does NOT immediately start the stream; it returns a SessionID ("accepted").
//
//  2. Event Bus (bus package):
//     A lightweight in-memory messaging system that decouples the API from the Worker.
//     Events include: SessionStart, SessionStop, SessionStateChange.
//
//  3. State Store (store package):
//     Persists the state of all active sessions (New, Tuning, Transcoding, Ready, etc.).
//     Supports in-memory (map-based) and persistent (BoltDB) backends.
//
//  4. Worker / Orchestrator (worker package):
//     Consumes events from the Bus.
//     - Acquires Tuner Leases (preventing over-subscription of Enigma2 tuners).
//     - Manages the FFmpeg Transcoder process life-cycle.
//     - Updates Session State in the Store.
//
//  5. HLS Delivery:
//     Segments generated by the Worker are served via `/api/v3/sessions/{sessionID}/hls/{file}`.
//
// Usage:
// The v3 system is enabled via `XG2G_V3_WORKER_ENABLED=true`.
// It currently runs alongside the v2 proxy but is intended to eventually replace it
// as the primary streaming engine in future releases.
package v3
