global:
  smtp_smarthost: "localhost:587"
  smtp_from: "xg2g-alerts@example.com"
  smtp_auth_username: "alerting@example.com"
  smtp_auth_password: "password"

route:
  group_by: ["alertname", "service"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h
  receiver: "web.hook"
  routes:
    - match:
        severity: critical
      receiver: "critical-alerts"
      group_wait: 10s
      repeat_interval: 1h
    - match:
        category: security
      receiver: "security-alerts"
      group_wait: 5s
      repeat_interval: 30m

receivers:
  - name: "web.hook"
    webhook_configs:
      - url: "http://host.docker.internal:5001/webhook"
        send_resolved: true

  - name: "critical-alerts"
    email_configs:
      - to: "oncall@example.com"
        subject: "🚨 CRITICAL: {{ .GroupLabels.service }} Alert"
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          {{ end }}
    webhook_configs:
      - url: "http://host.docker.internal:5001/webhook/critical"
        send_resolved: true

  - name: "security-alerts"
    email_configs:
      - to: "security@example.com"
        subject: "🛡️ SECURITY: {{ .GroupLabels.service }} Security Event"
        body: |
          Security Alert Detected:
          {{ range .Alerts }}
          Summary: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Time: {{ .StartsAt }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "service"]
