# xg2g OpenWebIF Alert Rules
# Production-ready Prometheus alerting for OpenWebIF integration and refresh failures
#
# Usage:
#   kubectl apply -f alert-rules-openwebif.yml
# Or add to your existing PrometheusRule resource

groups:
  - name: xg2g-openwebif-alerts
    rules:
      # Refresh Failures - Alert on any OpenWebIF request failures in the last 15 minutes
      - alert: XG2GRefreshFailures
        expr: increase(xg2g_openwebif_request_failures_total[15m]) > 0
        for: 2m
        labels:
          severity: warning
          service: xg2g
          component: openwebif
          category: integration
        annotations:
          summary: "xg2g OpenWebIF refresh failures detected"
          description: "{{ $value }} OpenWebIF request failures in the last 15 minutes. Service may be down or experiencing connectivity issues."
          runbook_url: "https://github.com/ManuGH/xg2g/docs/runbooks/refresh-failures.md"

      # Critical: Multiple consecutive failures indicate persistent issues
      - alert: XG2GRefreshFailuresCritical
        expr: increase(xg2g_openwebif_request_failures_total[30m]) >= 5
        for: 5m
        labels:
          severity: critical
          service: xg2g
          component: openwebif
          category: integration
        annotations:
          summary: "xg2g OpenWebIF experiencing persistent failures"
          description: "{{ $value }} OpenWebIF failures in the last 30 minutes. Immediate attention required."
          runbook_url: "https://github.com/ManuGH/xg2g/docs/runbooks/refresh-failures.md"

  - name: xg2g-scrape-monitoring
    rules:
      # Scrape Stall - Alert when xg2g metrics are not being scraped
      - alert: XG2GScrapeStall
        expr: absent(up{job="xg2g"} == 1)
        for: 10m
        labels:
          severity: warning
          service: xg2g
          component: monitoring
          category: observability
        annotations:
          summary: "xg2g metrics scraping has stalled"
          description: "Prometheus cannot scrape xg2g metrics for 10+ minutes. Check service health and network connectivity."
          runbook_url: "https://github.com/ManuGH/xg2g/docs/runbooks/metrics-scrape.md"

      # Critical: Extended outage
      - alert: XG2GScrapeStallCritical
        expr: absent(up{job="xg2g"} == 1)
        for: 30m
        labels:
          severity: critical
          service: xg2g
          component: monitoring
          category: observability
        annotations:
          summary: "xg2g metrics scraping down for 30+ minutes"
          description: "Extended metrics outage detected. Service may be completely down."

  - name: xg2g-refresh-health
    rules:
      # No successful refresh in expected timeframe (adjust based on your refresh interval)
      - alert: XG2GRefreshStale
        expr: time() - xg2g_last_refresh_timestamp > 7200 # 2 hours
        for: 5m
        labels:
          severity: warning
          service: xg2g
          component: refresh
          category: data-freshness
        annotations:
          summary: "xg2g refresh data is stale"
          description: "Last successful refresh was {{ $value | humanizeDuration }} ago. Expected refresh interval may be exceeded."

      # Zero channels indicates configuration or connectivity issues
      - alert: XG2GNoChannelsFound
        expr: xg2g_channels == 0
        for: 10m
        labels:
          severity: warning
          service: xg2g
          component: data
          category: data-integrity
        annotations:
          summary: "xg2g found zero channels in last refresh"
          description: "No channels discovered in recent refresh. Check OpenWebIF connectivity and bouquet configuration."

  - name: xg2g-performance-alerts
    rules:
      # Slow refresh operations
      - alert: XG2GSlowRefresh
        expr: histogram_quantile(0.95, rate(xg2g_refresh_duration_seconds_bucket[5m])) > 30
        for: 5m
        labels:
          severity: warning
          service: xg2g
          component: performance
          category: latency
        annotations:
          summary: "xg2g refresh operations are slow"
          description: "95th percentile refresh time is {{ $value | humanizeDuration }}. Consider investigating network or OpenWebIF performance."
