services:
  xg2g:
    image: ghcr.io/<OWNER>/xg2g@sha256:<DISTROLESS_DIGEST>
    container_name: xg2g
    ports:
      - "8080:8080"
    environment:
      - XG2G_DATA=/data
    volumes:
      - ./data:/data
    user: "65532:65532"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
      - seccomp=runtime/default
    restart: unless-stopped
