services:
  xg2g:
    image: ghcr.io/manugh/xg2g@sha256:e2fb2f4ad2e22a1616d73973654554b1a4027a5c36ef6c36db4c9c082321379f
    container_name: xg2g
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - XG2G_DATA=/data
      - XG2G_OWI_BASE=${XG2G_OWI_BASE}
      - XG2G_BOUQUET=${XG2G_BOUQUET}
      - XG2G_API_TOKEN=${XG2G_API_TOKEN}
      - XG2G_XMLTV=${XG2G_XMLTV:-xmltv.xml}
      - XG2G_LISTEN=:8080
      - XG2G_METRICS_LISTEN=:9090
      # EPG Configuration
      - XG2G_EPG_ENABLED=${XG2G_EPG_ENABLED:-false}
      - XG2G_EPG_DAYS=${XG2G_EPG_DAYS:-7}
      - XG2G_EPG_MAX_CONCURRENCY=${XG2G_EPG_MAX_CONCURRENCY:-5}
      - XG2G_EPG_TIMEOUT_MS=${XG2G_EPG_TIMEOUT_MS:-15000}
      - XG2G_EPG_RETRIES=${XG2G_EPG_RETRIES:-2}
    volumes:
      - ../data:/data
    user: "1000:1000"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
