services:
  xg2g:
    image: ghcr.io/<OWNER>/xg2g@sha256:<ALPINE_DIGEST>
    container_name: xg2g
    ports:
      - "8080:8080"
    environment:
      - XG2G_DATA=/data
      # - XG2G_OWI_BASE=http://receiver.local
      # - XG2G_BOUQUET=Favourites
      # - XG2G_LISTEN=:8080
    volumes:
      - ./data:/data
    user: "1000:1000"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
      - seccomp=runtime/default
    restart: unless-stopped
