services:
  xg2g:
    image: ghcr.io/manugh/xg2g@sha256:58d389f2abcad8be3e64e1ee9a7ddde71b2d7893e07fd9616d7cf6caacd687bb
    container_name: xg2g
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - XG2G_DATA=/data
      - XG2G_OWI_BASE=${XG2G_OWI_BASE}
      - XG2G_BOUQUET=${XG2G_BOUQUET}
      - XG2G_LISTEN=:8080
      - XG2G_METRICS_LISTEN=:9090
      - XG2G_API_TOKEN=${XG2G_API_TOKEN:-}
    volumes:
      - ./data:/data
    user: "65532:65532"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
