# Kubernetes Secret + ConfigMap für xg2g Production Deployment
#
# Usage:
# 1. Fill in actual values in the base64 encoded secrets below
# 2. kubectl apply -f k8s-secrets.yml
# 3. Apply the patched deployment: kubectl apply -f deploy/k8s-alpine.yaml

---
apiVersion: v1
kind: Secret
metadata:
  name: xg2g-secrets
  namespace: default
type: Opaque
data:
  # echo -n "your-secret-token" | base64
  api-token: eW91ci1zZWNyZXQtdG9rZW4=
  # echo -n "http://your-receiver.local" | base64
  owi-base: aHR0cDovL3lvdXItcmVjZWl2ZXIubG9jYWw=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xg2g-config
  namespace: default
data:
  XG2G_BOUQUET: "Premium"
  XG2G_DATA: "/data"
  XG2G_XMLTV: "xmltv.xml"
  XG2G_LISTEN: ":8080"
  XG2G_METRICS_LISTEN: ":9090"
  XG2G_OWI_TIMEOUT_MS: "20000"
  XG2G_OWI_RETRIES: "5"
  XG2G_OWI_BACKOFF_MS: "500"

---
# Deployment Patch - Add to your existing k8s-alpine.yaml
# Replace the env: section with this:
apiVersion: v1
kind: ConfigMap
metadata:
  name: xg2g-deployment-patch
data:
  env-patch.yaml: |
    env:
      - name: XG2G_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: xg2g-secrets
            key: api-token
      - name: XG2G_OWI_BASE
        valueFrom:
          secretKeyRef:
            name: xg2g-secrets
            key: owi-base
      - name: XG2G_BOUQUET
        valueFrom:
          configMapKeyRef:
            name: xg2g-config
            key: XG2G_BOUQUET
      - name: XG2G_DATA
        valueFrom:
          configMapKeyRef:
            name: xg2g-config
            key: XG2G_DATA
      - name: XG2G_XMLTV
        valueFrom:
          configMapKeyRef:
            name: xg2g-config
            key: XG2G_XMLTV
      - name: XG2G_LISTEN
        valueFrom:
          configMapKeyRef:
            name: xg2g-config
            key: XG2G_LISTEN
      - name: XG2G_METRICS_LISTEN
        valueFrom:
          configMapKeyRef:
            name: xg2g-config
            key: XG2G_METRICS_LISTEN
      - name: XG2G_OWI_TIMEOUT_MS
        valueFrom:
          configMapKeyRef:
            name: xg2g-config
            key: XG2G_OWI_TIMEOUT_MS
      - name: XG2G_OWI_RETRIES
        valueFrom:
          configMapKeyRef:
            name: xg2g-config
            key: XG2G_OWI_RETRIES
      - name: XG2G_OWI_BACKOFF_MS
        valueFrom:
          configMapKeyRef:
            name: xg2g-config
            key: XG2G_OWI_BACKOFF_MS
