apiVersion: apps/v1
kind: Deployment
metadata:
  name: xg2g
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xg2g
  template:
    metadata:
      labels:
        app: xg2g
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: xg2g
          image: ghcr.io/manugh/xg2g@sha256:6f5ec4041a0b9fada6c7fd59281ea6e0b298a397e4a86b58bc743dbfef6b9a3c
          imagePullPolicy: IfNotPresent
          env:
            - name: XG2G_DATA
              value: /data
            - name: XG2G_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: xg2g-secrets
                  key: api-token
            - name: XG2G_METRICS_LISTEN
              value: ":9090" # expose metrics endpoint for Prometheus
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: xg2g
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: xg2g
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 9090
      targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xg2g
  labels:
    app: xg2g
spec:
  selector:
    matchLabels:
      app: xg2g
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
