package ffmpeg

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/ManuGH/xg2g/internal/domain/session/ports"
	"github.com/ManuGH/xg2g/internal/hls/cmaf"
	"github.com/ManuGH/xg2g/internal/infra/ffmpeg/watchdog"
	"github.com/ManuGH/xg2g/internal/metrics"
	"github.com/ManuGH/xg2g/internal/pipeline/exec/enigma2"
	"github.com/ManuGH/xg2g/internal/pipeline/profiles"
	"github.com/ManuGH/xg2g/internal/pipeline/store"
	"github.com/ManuGH/xg2g/internal/procgroup"
	"github.com/ManuGH/xg2g/internal/telemetry"
	"github.com/rs/zerolog"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

// Start initiates the media process.
func (a *LocalAdapter) Start(ctx context.Context, spec ports.StreamSpec) (ports.RunHandle, error) {
	if spec.Source.Type == ports.SourceTuner && a.E2 != nil {
		if spec.Source.TunerSlot < 0 {
			return "", fmt.Errorf("invalid tuner slot: %d", spec.Source.TunerSlot)
		}
		tuner := enigma2.NewTuner(a.E2, spec.Source.TunerSlot, 10*time.Second)
		if err := tuner.Tune(ctx, spec.Source.ID); err != nil {
			return "", fmt.Errorf("tuning failed: %w", err)
		}
		a.Logger.Info().
			Str("session_id", spec.SessionID).
			Str("startup_phase", "tuner_tuned").
			Int("tuner_slot", spec.Source.TunerSlot).
			Str("service_ref", spec.Source.ID).
			Msg("tuner tune completed")
	}

	inputURL := ""
	switch spec.Source.Type {
	case ports.SourceTuner:
		if a.E2 == nil {
			return "", fmt.Errorf("tuner source requires enigma2 client")
		}
		streamURL, err := a.E2.ResolveStreamURL(ctx, spec.Source.ID)
		if err != nil {
			return "", fmt.Errorf("resolve stream url: %w", err)
		}
		streamURL = a.injectCredentialsIfAllowed(streamURL)
		a.Logger.Info().
			Str("session_id", spec.SessionID).
			Str("startup_phase", "stream_url_resolved").
			Str("resolved_url", sanitizeURLForLog(streamURL)).
			Msg("stream url resolved")

		chosenURL, err := a.selectStreamURL(ctx, spec.SessionID, spec.Source.ID, streamURL)
		if err != nil {
			return "", err
		}
		inputURL = chosenURL
		a.Logger.Info().
			Str("session_id", spec.SessionID).
			Str("startup_phase", "input_url_selected").
			Str("input_url", sanitizeURLForLog(inputURL)).
			Msg("stream input url selected")
	case ports.SourceURL:
		inputURL = spec.Source.ID
		a.Logger.Info().
			Str("session_id", spec.SessionID).
			Str("startup_phase", "input_url_selected").
			Str("input_url", sanitizeURLForLog(inputURL)).
			Msg("direct input url selected")
	}
	sourceKey := fpsCacheKey(spec.Source, inputURL)

	a.Logger.Info().
		Str("session_id", spec.SessionID).
		Str("startup_phase", "ffmpeg_args_build_started").
		Str("input_url", sanitizeURLForLog(inputURL)).
		Msg("ffmpeg args build started")
	// Span covering the playback decision + ffprobe probes (the untraced gap
	// between request and spawn). No-op when tracing is off. planCtx lets any
	// probe spans added later nest under this one.
	planCtx, planSpan := telemetry.Tracer("xg2g.ffmpeg").Start(ctx, "playback.plan",
		trace.WithAttributes(
			attribute.String("xg2g.session_id", spec.SessionID),
			attribute.String("xg2g.source_type", fmt.Sprintf("%v", spec.Source.Type)),
		),
	)
	plan, err := a.buildArgsWithPlan(planCtx, spec, inputURL)
	if err != nil {
		planSpan.RecordError(err)
		planSpan.SetStatus(codes.Error, "plan build failed")
		planSpan.End()
		return "", fmt.Errorf("failed to build args: %w", err)
	}
	planSpan.SetAttributes(attribute.String("xg2g.path_id", plan.pathID))
	planSpan.End()
	args := plan.args

	// Live A/V-sync (flag-gated, default off): re-route the HTTP relay through
	// a Go peek that measures the source's audio-before-keyframe "orphan" and
	// corrects it via a stdin pipe — audio atrim for -c:v copy (constant
	// audio-leads desync in iOS AVPlayer), input -ss for video transcode
	// (startup segment with a leading video hole while audio runs on). Any
	// peek/measure failure falls back to the unchanged direct-URL path.
	var avsyncStdin io.Reader
	avsyncSpec := spec
	avsyncSpec.Profile = plan.effectiveProfile
	if a.shouldAvsyncAtrim(avsyncSpec) {
		if orphan, stdin, ok := a.prepareAvsyncPipe(ctx, inputURL, spec.SessionID); ok {
			args = transformArgsForAvsyncPipeMode(args, orphan, !a.LiveAvsyncPipeNoTrim, avsyncSpec.Profile.TranscodeVideo)
			avsyncStdin = stdin
			if a.LiveAvsyncPipeNoTrim {
				a.Logger.Warn().
					Str("session_id", spec.SessionID).
					Str("startup_phase", "avsync_pipe_diagnostic").
					Msg("live-copy avsync diagnostic: stdin pipe active without audio trim")
			}
		}
	}

	a.Logger.Info().
		Str("session_id", spec.SessionID).
		Str("startup_phase", "ffmpeg_args_built").
		Int("arg_count", len(args)).
		Msg("ffmpeg args build finished")

	// #nosec G204 - BinPath is trusted from config; args are generated by strict internal logic (buildArgs)
	var cmd *exec.Cmd
	systemdRunPath, err := exec.LookPath("systemd-run")
	_, statErr := os.Stat("/run/systemd/system")
	// systemd-run --scope requires root or sufficient polkit permissions.
	// Non-root users will get a permission error even when the binary and
	// /run/systemd/system exist, so skip systemd-run when not root.
	useSystemd := os.Geteuid() == 0 && err == nil && statErr == nil

	if useSystemd {
		scopeName := fmt.Sprintf("xg2g-media-%s", spec.SessionID)
		systemdArgs := []string{"--scope", "--unit=" + scopeName, a.BinPath}
		systemdArgs = append(systemdArgs, args...)
		cmd = exec.CommandContext(ctx, systemdRunPath, systemdArgs...) // #nosec G204
	} else {
		cmd = exec.CommandContext(ctx, a.BinPath, args...) // #nosec G204
	}

	if avsyncStdin != nil {
		cmd.Stdin = avsyncStdin
	}
	procgroup.Set(cmd) // Mandatory for tree reaping
	// On ctx cancellation, gracefully SIGTERM the whole process group so ffmpeg
	// can flush its final segment + ENDLIST, instead of the stdlib default which
	// SIGKILLs the leader PID only. WaitDelay then bounds how long Wait blocks
	// after cancellation before the runtime force-kills the leader and closes I/O.
	cmd.Cancel = func() error {
		if cmd.Process == nil {
			return nil
		}
		return procgroup.TerminateGroup(cmd.Process.Pid)
	}
	if a.KillTimeout > 0 {
		cmd.WaitDelay = a.KillTimeout
	} else {
		cmd.WaitDelay = 5 * time.Second
	}

	stderr, err := cmd.StderrPipe()
	if err != nil {
		return "", fmt.Errorf("failed to pipe stderr: %w", err)
	}
	cmd.Stdout = nil

	// LL-HLS pipe mode: ffmpeg streams one fragmented MP4 on stdout and the
	// in-process segmenter produces the session artifacts. A manual os.Pipe
	// (instead of StdoutPipe) keeps the read end out of cmd.Wait's lifecycle
	// so the segmenter can drain the tail after process exit.
	var cmafRead, cmafWrite *os.File
	if plan.cmafSegment {
		cmafRead, cmafWrite, err = os.Pipe()
		if err != nil {
			return "", fmt.Errorf("cmaf pipe: %w", err)
		}
		cmd.Stdout = cmafWrite
	}

	// Span covering ffmpeg spawn -> first HLS segment (the user-perceived startup
	// latency). No-op when tracing is disabled; ended exactly once in the monitor.
	spawnedAt := time.Now()
	_, startupSpan := telemetry.Tracer("xg2g.ffmpeg").Start(ctx, "ffmpeg.startup",
		trace.WithAttributes(
			attribute.String("xg2g.session_id", spec.SessionID),
			attribute.String("xg2g.source_type", fmt.Sprintf("%v", spec.Source.Type)),
			attribute.String("xg2g.hw_backend", fmt.Sprintf("%v", argsHardwareBackend(args))),
			attribute.String("xg2g.path_id", plan.pathID),
		),
	)

	if a.inMemoryIngest && a.ingestServer != nil {
		a.ingestServer.Registry().GetOrCreate(spec.SessionID, nil)
	}

	if err := cmd.Start(); err != nil {
		if cmafRead != nil {
			_ = cmafRead.Close()
			_ = cmafWrite.Close()
		}
		startupSpan.RecordError(err)
		startupSpan.SetStatus(codes.Error, "ffmpeg start failed")
		startupSpan.End()
		return "", fmt.Errorf("ffmpeg start failed: %w", err)
	}
	if cmafRead != nil {
		// The child holds its own copy of the write end; closing ours makes
		// EOF reach the segmenter when ffmpeg exits.
		_ = cmafWrite.Close()
		segLogger := a.Logger.With().
			Str("component", "cmaf_segmenter").
			Str("session_id", spec.SessionID).
			Logger()
		segCfg := cmaf.Config{
			StreamID:          store.StreamID(spec.SessionID),
			Dir:               ports.SessionHLSDirForPolicy(a.HLSRoot, spec.SessionID, spec.Profile.DVRWindowSec),
			TargetDurationSec: plan.cmafTargetDurSec,
			ListSize:          plan.listSize,
			Logger:            segLogger,
			ShadowPublisher:   injectTestShadowStore(ctx, segLogger, a.Config),
		}
		go func(r *os.File) {
			defer func() { _ = r.Close() }()
			_ = cmaf.Run(ctx, r, segCfg)
		}(cmafRead)
	}

	pid := cmd.Process.Pid
	_ = WriteWorkerState(spec.SessionID, spec.Source.ID, spec.Profile.Name, pid)
	a.Logger.Info().
		Str("session_id", spec.SessionID).
		Str("startup_phase", "ffmpeg_started").
		Int("pid", pid).
		Msg("ffmpeg process started")
	handle := ports.RunHandle(fmt.Sprintf("%s-%d", spec.SessionID, pid))
	a.mu.Lock()
	a.activeProcs[handle] = cmd
	a.finalizedProfiles[handle] = plan.effectiveProfile
	// Execution truth: capture the plan parsed from the REAL argv we just handed
	// to the process, so observers report what ffmpeg runs, not a prediction.
	a.executedPlans[handle] = executedFFmpegPlanFromArgs(args)
	delete(a.processDetails, handle)
	a.mu.Unlock()

	go a.monitorProcessWithStartTimeout(ctx, handle, cmd, stderr, spec.SessionID, spec.Profile.DVRWindowSec, argsHardwareBackend(args), plan.pathID, a.startTimeoutForProfile(spec.Source.Type, plan.effectiveProfile), startupSpan, spawnedAt) // #nosec G118 -- goroutine receives the request-scoped ctx (first arg), not context.Background/TODO
	if sourceKey != "" {
		go a.learnFPSFromOutput(ctx, sourceKey, spec.SessionID, spec.Profile.DVRWindowSec)
	}

	metrics.RecordPipelineSpawn("ffmpeg", "admitted")
	return handle, nil
}

func (a *LocalAdapter) FinalizedProfile(handle ports.RunHandle) (ports.ProfileSpec, bool) {
	a.mu.Lock()
	defer a.mu.Unlock()

	profile, ok := a.finalizedProfiles[handle]
	if !ok {
		return ports.ProfileSpec{}, false
	}
	return profile, true
}

// ExecutedFFmpegPlan returns the execution-truth plan parsed from the real argv
// of the process launched for the handle. It is the un-lie-able source for
// "what ffmpeg runs", as opposed to any profile-derived prediction.
func (a *LocalAdapter) ExecutedFFmpegPlan(handle ports.RunHandle) (ports.ExecutedFFmpegPlan, bool) {
	a.mu.Lock()
	defer a.mu.Unlock()

	plan, ok := a.executedPlans[handle]
	if !ok {
		return ports.ExecutedFFmpegPlan{}, false
	}
	return plan, true
}

// shouldRecordHWRuntimeFailure reports whether a finished ffmpeg process should
// count as a hardware-encoder runtime failure for the sticky GPU->CPU demotion
// counter. Only a process that exited on its own (naturalExit) with a non-zero
// status AND that emitted a recognized encoder failure line qualifies. A
// deliberate stop (parentCtx cancel) or a watchdog stall termination kills the
// process too — procErr is non-nil in those cases — but that is not evidence
// the encoder failed, so it must not feed the demotion counter.
func shouldRecordHWRuntimeFailure(naturalExit bool, procErr error, runtimeFailureLine string) bool {
	if runtimeFailureLine == "" {
		return false
	}
	return naturalExit && procErr != nil
}

// processExitClassification captures how an ffmpeg process finished.
type processExitClassification struct {
	procErr          error
	resultErr        error
	naturalExit      bool
	watchdogConsumed bool
}

// awaitProcessExit blocks until the ffmpeg process finishes and classifies HOW
// it ended. naturalExit is true ONLY when the process exited on its own (the
// procErrCh case fired first). A watchdog stall and a context cancellation are
// both deliberate terminations and leave naturalExit false.
//
// Subtlety that this function exists to get right: the watchdog context is
// derived from parentCtx, so a parentCtx cancellation (user stop) ALSO cancels
// the watchdog, which then returns nil — i.e. wdErrCh receives nil at the same
// time parentCtx.Done() becomes ready. The select may pick either case, so the
// wdErr==nil branch is a context cancellation too and must NOT be treated as a
// natural exit (otherwise ~half of user stops would be misclassified).
func awaitProcessExit(
	parentCtx context.Context,
	procErrCh <-chan error,
	wdErrCh <-chan error,
	onWatchdogStall func(stallErr error),
	onContextCanceled func(),
) processExitClassification {
	var out processExitClassification
	select {
	case procErr := <-procErrCh:
		out.procErr = procErr
		// When the parent context is canceled (user stop), the proc may also
		// finish at the same instant, making both this case and parentCtx.Done()
		// ready. The select picks whichever is ready first, so we must check
		// parentCtx here too — a user stop is never a natural exit.
		if parentCtx.Err() != nil {
			out.resultErr = parentCtx.Err()
		} else {
			out.resultErr = procErr
			out.naturalExit = true
		}
	case wdErr := <-wdErrCh:
		out.watchdogConsumed = true
		if wdErr != nil {
			onWatchdogStall(wdErr)
			out.procErr = <-procErrCh
			out.resultErr = wdErr
			return out
		}
		// wdErr == nil: can happen either because parentCtx was canceled (user stop)
		// or because the watchdog finished naturally (e.g. progress=end).
		if parentCtx.Err() != nil {
			onContextCanceled()
			out.procErr = <-procErrCh
			out.resultErr = parentCtx.Err()
		} else {
			out.procErr = <-procErrCh
			out.resultErr = out.procErr
			out.naturalExit = true
		}
	case <-parentCtx.Done():
		onContextCanceled()
		out.procErr = <-procErrCh
		out.resultErr = parentCtx.Err()
	}
	return out
}

func (a *LocalAdapter) monitorProcessWithStartTimeout(parentCtx context.Context, handle ports.RunHandle, cmd *exec.Cmd, stderr io.ReadCloser, sessionID string, dvrWindowSec int, hwBackend profiles.GPUBackend, pathID string, startTimeout time.Duration, startupSpan trace.Span, spawnedAt time.Time) {
	defer func() {
		a.mu.Lock()
		a.removeActiveProcessLocked(handle, true)
		a.mu.Unlock()
	}()

	// End the startup span exactly once: success is recorded on first segment;
	// any other exit path (start timeout, early ffmpeg exit, ctx cancel) is an error.
	var sawFirstSegment atomic.Bool
	endStartupSpan := sync.OnceFunc(func() { startupSpan.End() })
	defer func() {
		if !sawFirstSegment.Load() {
			startupSpan.SetStatus(codes.Error, "ffmpeg exited before first HLS segment")
		}
		endStartupSpan()
	}()

	wd := watchdog.New(startTimeout, a.StallTimeout)

	if parentCtx == nil {
		parentCtx = context.Background()
	}
	wdCtx, wdCancel := context.WithCancel(parentCtx)
	defer wdCancel()
	observerCtx, observerCancel := context.WithCancel(parentCtx)
	defer observerCancel()

	wdErrCh := make(chan error, 1)
	go func() {
		wdErrCh <- wd.Run(wdCtx)
	}()

	runtimeFailureLine := ""
	scanDone := make(chan struct{})
	go func() {
		defer close(scanDone)

		// Forward lines to RingBuffer/Log and Watchdog.
		scanner := bufio.NewScanner(stderr)
		scanner.Split(scanFFmpegLogTokens)
		firstFrameLogged := false
		firstSegmentLogged := false
		outputObserverStarted := false

		logFFmpegLine := func(level zerolog.Level, line string, repeats int) {
			evt := a.Logger.WithLevel(level).Str("sessionId", sessionID).Str("ffmpeg_log", line)
			if repeats > 0 {
				evt = evt.Int("repeated", repeats)
			}
			evt.Msg("ffmpeg output")
		}
		dedup := newFFmpegLogDeduper(10 * time.Second)

		for scanner.Scan() {
			line := scanner.Text()
			if !firstFrameLogged {
				if frame, ok := parseFFmpegFrameCount(line); ok && frame > 0 {
					firstFrameLogged = true
					wd.ObserveProgress()
					a.writeFirstFrameMarker(sessionID, dvrWindowSec)
					a.Logger.Info().
						Str("session_id", sessionID).
						Str("startup_phase", "first_frame").
						Int("frame", frame).
						Msg("ffmpeg first frame observed")
				}
			}
			if !firstSegmentLogged {
				if segmentPath, ok := extractStartupSegmentPath(line); ok {
					firstSegmentLogged = true
					sawFirstSegment.Store(true)
					startupSpan.SetAttributes(attribute.Int64("xg2g.time_to_first_segment_ms", time.Since(spawnedAt).Milliseconds()))
					startupSpan.SetStatus(codes.Ok, "")
					endStartupSpan()
					wd.ObserveProgress()
					a.Logger.Info().
						Str("session_id", sessionID).
						Str("startup_phase", "first_segment_write").
						Str("segment_path", segmentPath).
						Msg("ffmpeg first segment write observed")
					if pathID != "" && !outputObserverStarted {
						outputObserverStarted = true
						go a.detector.observeRuntimePathCorrectness(observerCtx, handle, cmd, sessionID, pathID)
					}
				}
			}
			sanitizedLine := sanitizeFFmpegLogLine(line)
			a.recordRuntimeDiagnostics(handle, line, sanitizedLine)
			if detail := summarizeFFmpegFailureLine(sanitizedLine); detail != "" {
				a.recordProcessDetail(handle, detail)
			}
			if runtimeFailureLine == "" {
				switch hwBackend {
				case profiles.GPUBackendVAAPI:
					if isVAAPIRuntimeFailureLine(sanitizedLine) {
						runtimeFailureLine = sanitizedLine
					}
				case profiles.GPUBackendNVENC:
					if isNVENCRuntimeFailureLine(sanitizedLine) {
						runtimeFailureLine = sanitizedLine
					}
				}
			}
			dedup.observe(sanitizedLine, ffmpegLogLevel(sanitizedLine), logFFmpegLine)
			wd.ParseLine(line)
		}
		dedup.flush(logFFmpegLine)
		if scanErr := scanner.Err(); scanErr != nil {
			a.Logger.Warn().Err(scanErr).Str("sessionId", sessionID).Msg("ffmpeg stderr scan failed")
		}
	}()

	procErrCh := make(chan error, 1)
	go func() {
		// os/exec closes StderrPipe from Wait. Draining stderr first avoids
		// dropping the final FFmpeg failure lines that Health surfaces later.
		<-scanDone
		procErrCh <- cmd.Wait()
	}()

	classification := awaitProcessExit(
		parentCtx, procErrCh, wdErrCh,
		func(stallErr error) {
			metrics.IncLiveFFmpegStall("watchdog_timeout")
			a.recordProcessDetail(handle, "transcode stalled - no progress detected")
			a.Logger.Error().Err(stallErr).Str("sessionId", sessionID).Msg("watchdog triggered process termination")
			a.terminateProcessGroup(cmd, sessionID)
		},
		func() {
			a.terminateProcessGroup(cmd, sessionID)
		},
	)
	procErr := classification.procErr
	resultErr := classification.resultErr
	watchdogConsumed := classification.watchdogConsumed
	naturalExit := classification.naturalExit

	wdCancel()
	if !watchdogConsumed {
		if wdErr := <-wdErrCh; wdErr != nil {
			metrics.IncLiveFFmpegStall("watchdog_timeout")
			a.recordProcessDetail(handle, "transcode stalled - no progress detected")
			a.Logger.Error().Err(wdErr).Str("sessionId", sessionID).Msg("watchdog reported failure")
			if resultErr == nil {
				resultErr = wdErr
			}
		}
	}

	<-scanDone

	if shouldRecordHWRuntimeFailure(naturalExit, procErr, runtimeFailureLine) {
		switch hwBackend {
		case profiles.GPUBackendVAAPI:
			a.recordVAAPIRuntimeFailure(sessionID, runtimeFailureLine)
		case profiles.GPUBackendNVENC:
			a.recordNVENCRuntimeFailure(sessionID, runtimeFailureLine)
		}
	}

	if procErr != nil {
		a.recordProcessDetail(handle, summarizeProcessExit(procErr))
		a.Logger.Debug().Err(procErr).Str("sessionId", sessionID).Msg("ffmpeg process exited")
		return
	}
	if resultErr != nil {
		return
	}
	a.clearProcessDetail(handle)
}

func (a *LocalAdapter) startTimeoutForProfile(sourceType ports.SourceType, profile ports.ProfileSpec) time.Duration {
	timeout := a.StartTimeout
	if timeout <= 0 {
		return timeout
	}
	if sourceType == ports.SourceFile || !profile.TranscodeVideo {
		return timeout
	}
	if strings.TrimSpace(profile.HWAccel) != "" {
		return timeout
	}

	overrideFloor := 30 * time.Second
	if profile.EffectiveRuntimeMode == ports.RuntimeModeHQ50 {
		overrideFloor = 60 * time.Second
	} else {
		normalizedProfile := profiles.NormalizeRequestedProfileID(profile.Name)
		if normalizedProfile != profiles.ProfileSafari && normalizedProfile != profiles.ProfileSafariRuntimeHQ {
			return timeout
		}
	}

	override := a.Config.SafariCPUStartTimeoutOverride
	if override <= 0 {
		override = overrideFloor
	}
	if override < timeout {
		override = timeout
	}
	if override > 120*time.Second {
		override = 120 * time.Second
	}
	if override > timeout {
		return override
	}
	return timeout
}

func argsHardwareBackend(args []string) profiles.GPUBackend {
	for i := range args {
		if args[i] == "-vaapi_device" {
			return profiles.GPUBackendVAAPI
		}
		switch args[i] {
		case "h264_nvenc", "hevc_nvenc", "av1_nvenc":
			return profiles.GPUBackendNVENC
		}
	}
	return profiles.GPUBackendNone
}

func (a *LocalAdapter) writeFirstFrameMarker(sessionID string, dvrWindowSec int) {
	if !ports.IsSafeSessionID(sessionID) {
		return
	}
	markerPath := ports.SessionFirstFrameMarkerPathForPolicy(a.HLSRoot, sessionID, dvrWindowSec)
	if markerPath != "" {
		if err := os.MkdirAll(filepath.Dir(markerPath), 0o750); err != nil {
			a.Logger.Warn().Err(err).Str("session_id", sessionID).Msg("failed to prep marker dir")
		} else {
			_ = os.WriteFile(markerPath, []byte(time.Now().UTC().Format(time.RFC3339Nano)), 0o600)
		}
	}

}

// Stop terminates the process.
func (a *LocalAdapter) Stop(ctx context.Context, handle ports.RunHandle) error {
	a.mu.Lock()
	cmd, exists := a.activeProcs[handle]
	if exists {
		a.removeActiveProcessLocked(handle, false)
	}
	a.mu.Unlock()

	if !exists {
		return nil // Idempotent
	}

	if cmd.Process != nil {
		return a.killProcessGroup(cmd)
	}

	return nil
}

func (a *LocalAdapter) removeActiveProcessLocked(handle ports.RunHandle, archiveDetail bool) {
	delete(a.activeProcs, handle)
	delete(a.finalizedProfiles, handle)
	delete(a.executedPlans, handle)
	delete(a.runtimeDiagnostics, handle)
	if archiveDetail {
		a.archiveProcessDetailLocked(handle)
	}
	delete(a.processDetails, handle)
}

func (a *LocalAdapter) archiveProcessDetailLocked(handle ports.RunHandle) {
	detail := strings.TrimSpace(a.processDetails[handle])
	if detail == "" {
		return
	}
	if a.completedProcessDetails == nil {
		a.completedProcessDetails = make(map[ports.RunHandle]string)
	}
	if _, exists := a.completedProcessDetails[handle]; !exists {
		a.completedProcessDetailOrder = append(a.completedProcessDetailOrder, handle)
	}
	a.completedProcessDetails[handle] = detail
	for len(a.completedProcessDetailOrder) > maxCompletedProcessDetails {
		evict := a.completedProcessDetailOrder[0]
		a.completedProcessDetailOrder = a.completedProcessDetailOrder[1:]
		delete(a.completedProcessDetails, evict)
	}
}

func (a *LocalAdapter) terminateProcessGroup(cmd *exec.Cmd, sessionID string) {
	if err := a.killProcessGroup(cmd); err != nil {
		a.Logger.Warn().Err(err).Str("sessionId", sessionID).Msg("failed to terminate ffmpeg process group")
	}
}

func (a *LocalAdapter) killProcessGroup(cmd *exec.Cmd) error {
	if cmd == nil || cmd.Process == nil {
		return nil
	}
	// Non-reaping group ladder: the monitor goroutine's cmd.Wait is the sole
	// reaper, so this must not call Wait or it would race the exit status
	// (corrupting exit classification, e.g. a spurious GPU->CPU demotion).
	return procgroup.KillGroupGraceful(cmd.Process.Pid, 2*time.Second, a.KillTimeout)
}

func (a *LocalAdapter) Health(ctx context.Context, handle ports.RunHandle) ports.HealthStatus {
	a.mu.Lock()
	_, exists := a.activeProcs[handle]
	diagnostics := a.runtimeDiagnostics[handle]
	a.mu.Unlock()
	if !exists {
		// monitorProcess has finished — scanner drained, detail is final.
		return ports.HealthStatus{
			Healthy:     false,
			Message:     a.processStatusMessage(handle, "process not found"),
			LastCheck:   time.Now(),
			Diagnostics: diagnostics,
		}
	}

	return ports.HealthStatus{
		Healthy:     true,
		Message:     "process active",
		LastCheck:   time.Now(),
		Diagnostics: diagnostics,
	}
}

func (a *LocalAdapter) recordProcessDetail(handle ports.RunHandle, detail string) {
	detail = strings.TrimSpace(detail)
	if detail == "" {
		return
	}
	a.mu.Lock()
	defer a.mu.Unlock()
	current := a.processDetails[handle]
	if processDetailPriority(detail) >= processDetailPriority(current) {
		a.processDetails[handle] = detail
	}
}

func (a *LocalAdapter) clearProcessDetail(handle ports.RunHandle) {
	a.mu.Lock()
	delete(a.processDetails, handle)
	a.mu.Unlock()
}

func (a *LocalAdapter) processStatusMessage(handle ports.RunHandle, fallback string) string {
	a.mu.Lock()
	defer a.mu.Unlock()
	if detail := strings.TrimSpace(a.processDetails[handle]); detail != "" {
		delete(a.processDetails, handle)
		return detail
	}
	if detail := strings.TrimSpace(a.completedProcessDetails[handle]); detail != "" {
		delete(a.completedProcessDetails, handle)
		return detail
	}
	return fallback
}

func processDetailPriority(detail string) int {
	switch detail {
	case "runtime path correctness failed - black output detected":
		return 55
	case "transcode stalled - no progress detected":
		return 50
	case "copy output missing codec parameters":
		return 45
	case "upstream stream ended prematurely":
		return 40
	case "failed to open upstream input", "upstream input/output error":
		return 30
	case "invalid upstream input data":
		return 20
	case "process exited unexpectedly":
		return 10
	default:
		return 0
	}
}
