package ffmpeg

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/ManuGH/xg2g/internal/domain/session/ports"
	"github.com/rs/zerolog"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestE2E_ProductiveBackendABRExecution tests that the productive LocalAdapter FFmpeg pipeline
// spawns FFmpeg, generates a valid master.m3u8 with 3-tier variant playlists and .ts segments on disk,
// maintains a constant PID, and produces aligned MPEG-TS PTS timestamps across variants.
func TestE2E_ProductiveBackendABRExecution(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping E2E test in short mode")
	}

	tempDir := t.TempDir()

	// 1. Generate a real 20-second 1080p25 MPEG-TS input file
	inputFile := filepath.Join(tempDir, "input.ts")
	genCmd := exec.Command("ffmpeg",
		"-hide_banner", "-loglevel", "error",
		"-f", "lavfi", "-i", "testsrc=size=1920x1080:rate=25:duration=20",
		"-f", "lavfi", "-i", "sine=frequency=1000:sample_rate=48000:duration=20",
		"-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
		"-c:a", "aac", "-b:a", "128k",
		"-f", "mpegts", "-y", inputFile,
	)
	require.NoError(t, genCmd.Run(), "generating test input file must succeed")

	// 2. Serve input.ts over local HTTP server to mimic live tuner stream
	tsBytes, err := os.ReadFile(inputFile)
	require.NoError(t, err)

	tsServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "video/mp2t")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write(tsBytes)
	}))
	defer tsServer.Close()

	// 3. Setup LocalAdapter
	hlsDir := filepath.Join(tempDir, "hls")
	adapter := NewLocalAdapter(
		"ffmpeg",
		"ffprobe",
		hlsDir,
		nil,
		zerolog.New(os.Stdout).With().Timestamp().Logger(),
		"",
		"",
		0,
		0,
		false,
		2*time.Second,
		2,
		0,
		0,
		"",
	)

	ctx, cancel := context.WithTimeout(context.Background(), 25*time.Second)
	defer cancel()

	sessionID := "sess-e2e-backend-abr"
	spec := ports.StreamSpec{
		SessionID: sessionID,
		Mode:      ports.ModeLive,
		Format:    ports.FormatHLS,
		Source:    ports.StreamSource{Type: ports.SourceURL, ID: tsServer.URL + "/stream.ts"},
		Profile: ports.ProfileSpec{
			Name:              "hq25",
			TranscodeVideo:    true,
			VideoCodec:        "h264",
			VideoSourceHeight: 1080,
			EnableABR:         true,
		},
	}

	// 4. Start productive LocalAdapter pipeline
	handle, err := adapter.Start(ctx, spec)
	require.NoError(t, err)
	require.NotEmpty(t, handle)

	// Verify constant PID
	adapter.mu.Lock()
	activeCmd := adapter.activeProcs[handle]
	adapter.mu.Unlock()

	require.NotNil(t, activeCmd)
	require.NotNil(t, activeCmd.Process)
	pid := activeCmd.Process.Pid
	t.Logf("[E2E TEST] Backend FFmpeg started with PID: %d", pid)

	// 5. Poll for master.m3u8 and variant segments
	sessionDir := filepath.Join(hlsDir, sessionID)
	masterPath := filepath.Join(sessionDir, "master.m3u8")

	require.Eventually(t, func() bool {
		info, err := os.Stat(masterPath)
		return err == nil && info.Size() > 0
	}, 15*time.Second, 500*time.Millisecond, "master.m3u8 should be generated by backend FFmpeg")

	masterContent, err := os.ReadFile(masterPath)
	require.NoError(t, err)
	masterStr := string(masterContent)

	t.Logf("[E2E TEST] Generated master.m3u8:\n%s", masterStr)
	assert.Contains(t, masterStr, "#EXTM3U")
	assert.Contains(t, masterStr, "1080p/index.m3u8")
	assert.Contains(t, masterStr, "720p/index.m3u8")
	assert.Contains(t, masterStr, "480p/index.m3u8")

	// Wait for media segments in all 3 variants
	require.Eventually(t, func() bool {
		matches1080, _ := filepath.Glob(filepath.Join(sessionDir, "1080p", "*.ts"))
		matches720, _ := filepath.Glob(filepath.Join(sessionDir, "720p", "*.ts"))
		matches480, _ := filepath.Glob(filepath.Join(sessionDir, "480p", "*.ts"))
		return len(matches1080) >= 2 && len(matches720) >= 2 && len(matches480) >= 2
	}, 15*time.Second, 500*time.Millisecond, "All 3 variants (1080p, 720p, 480p) must publish TS segments")

	// 6. Verify PID remains 100% constant
	adapter.mu.Lock()
	currentCmd := adapter.activeProcs[handle]
	adapter.mu.Unlock()
	require.NotNil(t, currentCmd)
	require.NotNil(t, currentCmd.Process)
	assert.Equal(t, pid, currentCmd.Process.Pid, "FFmpeg PID must remain constant during execution")

	// 7. Run ffprobe PTS alignment check on generated backend segments
	ts1080, _ := filepath.Glob(filepath.Join(sessionDir, "1080p", "*.ts"))
	ts720, _ := filepath.Glob(filepath.Join(sessionDir, "720p", "*.ts"))
	ts480, _ := filepath.Glob(filepath.Join(sessionDir, "480p", "*.ts"))

	pts1080 := extractFirstPacketPTS(t, ts1080[0])
	pts720 := extractFirstPacketPTS(t, ts720[0])
	pts480 := extractFirstPacketPTS(t, ts480[0])

	t.Logf("[E2E PTS CHECK] 1080p first PTS: %.3fs | 720p first PTS: %.3fs | 480p first PTS: %.3fs", pts1080, pts720, pts480)

	delta1 := absFloat(pts1080 - pts720)
	delta2 := absFloat(pts720 - pts480)
	assert.LessOrEqual(t, delta1, 0.05, "PTS delta between 1080p and 720p must be <= 50ms")
	assert.LessOrEqual(t, delta2, 0.05, "PTS delta between 720p and 480p must be <= 50ms")

	// Clean stop
	_ = adapter.Stop(context.Background(), handle)
}

func extractFirstPacketPTS(t *testing.T, tsFile string) float64 {
	out, err := exec.Command("ffprobe",
		"-v", "error",
		"-show_entries", "packet=pts_time",
		"-select_streams", "v:0",
		"-read_intervals", "%+#1",
		"-of", "default=noprint_wrappers=1:nokey=1",
		tsFile,
	).Output()
	require.NoError(t, err, "ffprobe must succeed on TS file: %s", tsFile)

	valStr := strings.TrimSpace(string(out))
	pts, err := strconv.ParseFloat(valStr, 64)
	require.NoError(t, err, "failed to parse pts float: %s", valStr)
	return pts
}

func absFloat(f float64) float64 {
	if f < 0 {
		return -f
	}
	return f
}
