// Copyright (c) 2025 ManuGH
// Licensed under the PolyForm Noncommercial License 1.0.0

package middleware

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestObservability_ProblemResponseMatchesHeaderTruth(t *testing.T) {
	// Setup a router with the full stack
	r := NewRouter(StackConfig{
		EnableCORS:            true,
		AllowedOrigins:        nil, // Empty allowlist to trigger CSRF 403 easily
		EnableSecurityHeaders: false,
		EnableMetrics:         false,
		EnableLogging:         false,
		EnableRateLimit:       false,
	})

	r.Post("/mutate", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})

	// 1. Request with ad-hoc Request-ID
	customID := "test-req-id-123"
	req := httptest.NewRequest(http.MethodPost, "/mutate", nil)
	req.Host = "example.com"
	req.Header.Set("X-Request-ID", customID)
	// No Same-Origin headers to trigger CSRF 403

	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	// Verify CSRF Block
	assert.Equal(t, http.StatusForbidden, w.Code)

	// Assert: Header Presence
	headerID := w.Header().Get("X-Request-ID")
	assert.Equal(t, customID, headerID, "Response Header X-Request-ID must match request input")

	// Assert: JSON Body contains requestId
	var body map[string]any
	err := json.Unmarshal(w.Body.Bytes(), &body)
	require.NoError(t, err)

	bodyID, ok := body["requestId"].(string)
	assert.True(t, ok, "requestId must be present in JSON body")
	assert.Equal(t, headerID, bodyID, "Request-ID in Body must match Header truth")
	assert.Equal(t, "CSRF_FORBIDDEN", body["code"])
}

func TestObservability_GeneratedIDMatchesBody(t *testing.T) {
	// Setup a router with the full stack
	r := NewRouter(StackConfig{
		EnableCORS:     true,
		AllowedOrigins: nil,
	})

	r.Post("/mutate", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})

	// 2. Request WITHOUT Request-ID (should be generated)
	req := httptest.NewRequest(http.MethodPost, "/mutate", nil)
	req.Host = "example.com"

	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	assert.Equal(t, http.StatusForbidden, w.Code)

	headerID := w.Header().Get("X-Request-ID")
	assert.NotEmpty(t, headerID, "X-Request-ID should be generated by middleware")

	var body map[string]any
	err := json.Unmarshal(w.Body.Bytes(), &body)
	require.NoError(t, err)

	bodyID, ok := body["requestId"].(string)
	assert.True(t, ok)
	assert.Equal(t, headerID, bodyID, "Generated ID must be consistent across Header and Body")
}
