// Copyright (c) 2025 ManuGH
// Licensed under the PolyForm Noncommercial License 1.0.0
// Since v2.0.0, this software is restricted to non-commercial use only.

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/ManuGH/xg2g/internal/config"
)

func writeGeneratedCode(backendRoot string, entries []config.ConfigEntry) error {
	if err := writeGeneratedMergeEnv(backendRoot, entries); err != nil {
		return fmt.Errorf("write merge_env_gen.go: %w", err)
	}
	return nil
}

func getFieldType(fieldPath string) reflect.Type {
	appConfigType := reflect.TypeOf(config.AppConfig{})
	parts := strings.Split(fieldPath, ".")
	curr := appConfigType
	for _, part := range parts {
		if curr.Kind() == reflect.Ptr {
			curr = curr.Elem()
		}
		if curr.Kind() != reflect.Struct {
			return nil
		}
		field, ok := curr.FieldByName(part)
		if !ok {
			return nil
		}
		curr = field.Type
	}
	return curr
}

func writeGeneratedMergeEnv(backendRoot string, entries []config.ConfigEntry) error {
	var buf bytes.Buffer
	buf.WriteString(`// Code generated by configgen. DO NOT EDIT.
// Copyright (c) 2025 ManuGH
// Licensed under the PolyForm Noncommercial License 1.0.0

package config

// mergeEnvConfigGenerated applies registry-defined environment variables to AppConfig.
func (l *Loader) mergeEnvConfigGenerated(cfg *AppConfig) {
`)

	sorted := make([]config.ConfigEntry, 0, len(entries))
	for _, e := range entries {
		if e.Env != "" && e.FieldPath != "" {
			sorted = append(sorted, e)
		}
	}
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Env < sorted[j].Env
	})

	durationSeq := reflect.TypeOf(time.Second)

	for _, e := range sorted {
		field := "cfg." + e.FieldPath
		envVar := e.Env

		// Handle specific custom types
		if e.Path == "api.allowedOrigins" || e.Path == "api.tokenScopes" || e.Path == "api.playbackDecisionPreviousKeys" || e.Path == "network.outbound.allow.hosts" || e.Path == "network.outbound.allow.cidrs" || e.Path == "network.outbound.allow.schemes" || e.Path == "network.lan.allow.cidrs" || e.Path == "rateLimit.whitelist" || e.Path == "monetization.requiredScopes" {
			buf.WriteString(fmt.Sprintf("\t%s = parseCommaSeparated(l.envString(%q, \"\"), %s)\n", field, envVar, field))
			continue
		}
		if e.Path == "engine.tunerSlots" {
			continue // custom ParseTunerSlots in mergeEnvTunerSlots
		}
		if e.Path == "network.outbound.allow.ports" {
			buf.WriteString(fmt.Sprintf("\t%s = parseCommaSeparatedInts(l.envString(%q, \"\"), %s)\n", field, envVar, field))
			continue
		}
		if e.Path == "api.tokens" {
			buf.WriteString(fmt.Sprintf("\tif tokens, err := parseScopedTokens(l.envString(%q, \"\"), %s); err == nil {\n\t\t%s = tokens\n\t}\n", envVar, field, field))
			continue
		}
		if e.Path == "connectivity.publishedEndpoints" {
			continue // custom unmarshal in mergeEnvConnectivity
		}

		fieldType := getFieldType(e.FieldPath)
		if fieldType == nil {
			continue
		}

		if fieldType == durationSeq {
			buf.WriteString(fmt.Sprintf("\t%s = l.envDuration(%q, %s)\n", field, envVar, field))
		} else if fieldType.Kind() == reflect.Bool {
			buf.WriteString(fmt.Sprintf("\t%s = l.envBool(%q, %s)\n", field, envVar, field))
		} else if fieldType.Kind() == reflect.Int || fieldType.Kind() == reflect.Int64 {
			buf.WriteString(fmt.Sprintf("\t%s = l.envInt(%q, %s)\n", field, envVar, field))
		} else if fieldType.Kind() == reflect.Float64 {
			buf.WriteString(fmt.Sprintf("\t%s = l.envFloat(%q, %s)\n", field, envVar, field))
		} else if fieldType.Kind() == reflect.String {
			buf.WriteString(fmt.Sprintf("\t%s = l.envString(%q, %s)\n", field, envVar, field))
		}
	}

	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated merge_env error: %w\nContent:\n%s", err, buf.String())
	}

	outputPath := filepath.Join(backendRoot, "internal", "config", "merge_env_gen.go")
	return os.WriteFile(outputPath, formatted, 0600)
}
