package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

func writeConfigInventory(root string) error {
	files, err := trackedFiles(root)
	if err != nil {
		return fmt.Errorf("tracked files: %w", err)
	}

	sort.Strings(files)
	var b strings.Builder
	b.WriteString("# Configuration Surfaces Inventory (Generated)\n\n")
	b.WriteString("This file is generated by `cmd/configgen` and lists files referencing `XG2G_*` keys.\n\n")
	for _, f := range files {
		fmt.Fprintf(&b, "- `%s`\n", f)
	}

	path := filepath.Join(root, configInventory)
	if err := os.WriteFile(path, []byte(b.String()), 0600); err != nil {
		return fmt.Errorf("write inventory: %w", err)
	}
	return nil
}

func trackedFiles(root string) ([]string, error) {
	cmd := exec.Command("git", "ls-files", "-z")
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("git ls-files failed: %w", err)
	}
	if len(out) == 0 {
		return nil, nil
	}
	paths := bytes.Split(out, []byte{0})
	files := make([]string, 0, len(paths))
	for _, p := range paths {
		if len(p) == 0 {
			continue
		}
		rel := string(p)
		if !shouldScanFile(rel) {
			continue
		}
		abs := filepath.Join(root, rel)
		if fileContains(abs, "XG2G_") {
			files = append(files, rel)
		}
	}
	return files, nil
}

func shouldScanFile(path string) bool {
	normalized := filepath.ToSlash(path)
	// Generated UI bundles can contain incidental "XG2G_" substrings and cause
	// nondeterministic inventory drift across environments. Keep inventory focused
	// on source/config surfaces, not compiled embed artifacts.
	if strings.HasPrefix(normalized, "internal/control/http/dist/assets/") ||
		strings.HasPrefix(normalized, "backend/internal/control/http/dist/assets/") {
		return false
	}

	base := filepath.Base(path)
	if base == "Dockerfile" || strings.HasPrefix(base, "Dockerfile.") {
		return true
	}
	ext := strings.ToLower(filepath.Ext(path))
	switch ext {
	case ".go", ".md", ".yaml", ".yml", ".json", ".env", ".txt", ".sh", ".service", ".ts", ".tsx", ".js", ".toml":
		return true
	default:
		return false
	}
}

func fileContains(path, needle string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}
	if info.Size() > 1024*1024 {
		return false
	}
	// #nosec G304 -- intended CLI behavior
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return bytes.Contains(data, []byte(needle))
}
