#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

TARGET_PATHS=(
  "internal/api/server_gen.go"
  "internal/control/http/v3/server_gen.go"
  "openapi/v3.normative.snapshot.yaml"
  "webui/src/client-ts"
)

before_diff="$(mktemp)"
after_diff="$(mktemp)"
before_untracked="$(mktemp)"
after_untracked="$(mktemp)"
trap 'rm -f "$before_diff" "$after_diff" "$before_untracked" "$after_untracked"' EXIT

git diff -- "${TARGET_PATHS[@]}" > "$before_diff"
git ls-files --others --exclude-standard -- "${TARGET_PATHS[@]}" | LC_ALL=C sort > "$before_untracked"

./scripts/gen-openapi-hard-mode.sh

echo "Verifying generated marker integrity for webui client..."
marker='// This file is auto-generated by @hey-api/openapi-ts'
marker_count=0
missing_marker=0
while IFS= read -r -d '' file; do
  marker_count=$((marker_count + 1))
  first_line="$(head -n 1 "$file" || true)"
  if [[ "$first_line" != "$marker"* ]]; then
    echo "❌ Missing generated marker: $file"
    missing_marker=1
  fi
done < <(find webui/src/client-ts -type f -name '*.gen.ts' ! -name '._*' -print0)

if [ "$marker_count" -eq 0 ]; then
  echo "❌ No generated *.gen.ts files found under webui/src/client-ts"
  exit 1
fi
if [ "$missing_marker" -ne 0 ]; then
  echo "❌ Generated marker integrity check failed"
  exit 1
fi
echo "✅ Generated marker integrity passed ($marker_count files)"

git diff -- "${TARGET_PATHS[@]}" > "$after_diff"
git ls-files --others --exclude-standard -- "${TARGET_PATHS[@]}" | LC_ALL=C sort > "$after_untracked"

if ! cmp -s "$before_diff" "$after_diff" || ! cmp -s "$before_untracked" "$after_untracked"; then
  echo "❌ OpenAPI hard-mode drift detected in generated artifacts."
  echo "   Run: make gen-openapi-hard"
  echo ""
  echo "Status for tracked scope:"
  git status --short -- "${TARGET_PATHS[@]}"
  exit 1
fi

echo "✅ OpenAPI hard-mode drift lock passed"
