// Code generated by configgen. DO NOT EDIT.
// Copyright (c) 2025 ManuGH
// Licensed under the PolyForm Noncommercial License 1.0.0

package config

import (
	"strings"

	"github.com/ManuGH/xg2g/internal/validate"
)

// validateConfigGenerated applies registry-driven validation rules to AppConfig.
func validateConfigGenerated(v *validate.Validator, cfg AppConfig) {
	if cfg.EPGEnabled {
		v.Range("EPGDays", cfg.EPGDays, 1, 14)
	}
	if cfg.EPGEnabled {
		v.Range("EPGMaxConcurrency", cfg.EPGMaxConcurrency, 1, 10)
	}
	if cfg.EPGEnabled {
		v.Range("EPGRetries", cfg.EPGRetries, 0, 5)
	}
	if cfg.EPGEnabled {
		v.Range("EPGTimeoutMS", cfg.EPGTimeoutMS, 100, 60000)
	}
	if cfg.EPGEnabled {
		v.Range("FuzzyMax", cfg.FuzzyMax, 0, 10)
	}
	if cfg.LogLevel != "" {
		v.OneOf("LogLevel", strings.ToLower(cfg.LogLevel), []string{"debug", "info", "warn", "error", "fatal", "panic", "disabled", "trace"})
	}
}
