# Grafana datasource configuration for Prometheus
# This file configures Prometheus as the default data source for Grafana

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
