// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddTimerData, AddTimerErrors, AddTimerResponses, CreateSeriesRuleData, CreateSeriesRuleResponses, CreateSessionData, CreateSessionErrors, CreateSessionResponses, DeleteRecordingData, DeleteRecordingErrors, DeleteRecordingResponses, DeleteSeriesRuleData, DeleteSeriesRuleErrors, DeleteSeriesRuleResponses, DeleteStreamsIdData, DeleteStreamsIdErrors, DeleteStreamsIdResponses, DeleteTimerData, DeleteTimerErrors, DeleteTimerResponses, GetDvrCapabilitiesData, GetDvrCapabilitiesResponses, GetDvrStatusData, GetDvrStatusResponses, GetEpgData, GetEpgResponses, GetLogsData, GetLogsResponses, GetRecordingHlsCustomSegmentData, GetRecordingHlsCustomSegmentResponses, GetRecordingHlsPlaylistData, GetRecordingHlsPlaylistErrors, GetRecordingHlsPlaylistResponses, GetRecordingsData, GetRecordingsResponses, GetRecordingStreamData, GetRecordingStreamErrors, GetSeriesRulesData, GetSeriesRulesResponses, GetServicesBouquetsData, GetServicesBouquetsResponses, GetServicesData, GetServicesResponses, GetStreamsData, GetStreamsResponses, GetSystemConfigData, GetSystemConfigResponses, GetSystemHealthData, GetSystemHealthResponses, GetTimerData, GetTimerErrors, GetTimerResponses, GetTimersData, GetTimersResponses, PostServicesByIdToggleData, PostServicesByIdToggleErrors, PostServicesByIdToggleResponses, PostSystemRefreshData, PostSystemRefreshErrors, PostSystemRefreshResponses, PreviewConflictsData, PreviewConflictsResponses, PutSystemConfigData, PutSystemConfigErrors, PutSystemConfigResponses, RunAllSeriesRulesData, RunAllSeriesRulesResponses, RunSeriesRuleData, RunSeriesRuleErrors, RunSeriesRuleResponses, UpdateTimerData, UpdateTimerErrors, UpdateTimerResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get system health
 */
export const getSystemHealth = <ThrowOnError extends boolean = false>(options?: Options<GetSystemHealthData, ThrowOnError>) => (options?.client ?? client).get<GetSystemHealthResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/system/health',
    ...options
});

/**
 * Get system configuration
 */
export const getSystemConfig = <ThrowOnError extends boolean = false>(options?: Options<GetSystemConfigData, ThrowOnError>) => (options?.client ?? client).get<GetSystemConfigResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/system/config',
    ...options
});

/**
 * Update system configuration
 */
export const putSystemConfig = <ThrowOnError extends boolean = false>(options: Options<PutSystemConfigData, ThrowOnError>) => (options.client ?? client).put<PutSystemConfigResponses, PutSystemConfigErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/system/config',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Trigger data refresh (EPG/Channels)
 */
export const postSystemRefresh = <ThrowOnError extends boolean = false>(options?: Options<PostSystemRefreshData, ThrowOnError>) => (options?.client ?? client).post<PostSystemRefreshResponses, PostSystemRefreshErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/system/refresh',
    ...options
});

/**
 * List all bouquets
 */
export const getServicesBouquets = <ThrowOnError extends boolean = false>(options?: Options<GetServicesBouquetsData, ThrowOnError>) => (options?.client ?? client).get<GetServicesBouquetsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/services/bouquets',
    ...options
});

/**
 * Get EPG data
 */
export const getEpg = <ThrowOnError extends boolean = false>(options?: Options<GetEpgData, ThrowOnError>) => (options?.client ?? client).get<GetEpgResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/epg',
    ...options
});

/**
 * List all services (channels)
 */
export const getServices = <ThrowOnError extends boolean = false>(options?: Options<GetServicesData, ThrowOnError>) => (options?.client ?? client).get<GetServicesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/services',
    ...options
});

/**
 * Toggle service enabled state
 */
export const postServicesByIdToggle = <ThrowOnError extends boolean = false>(options: Options<PostServicesByIdToggleData, ThrowOnError>) => (options.client ?? client).post<PostServicesByIdToggleResponses, PostServicesByIdToggleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/services/{id}/toggle',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List active streams
 */
export const getStreams = <ThrowOnError extends boolean = false>(options?: Options<GetStreamsData, ThrowOnError>) => (options?.client ?? client).get<GetStreamsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/streams',
    ...options
});

/**
 * Browse recordings
 */
export const getRecordings = <ThrowOnError extends boolean = false>(options?: Options<GetRecordingsData, ThrowOnError>) => (options?.client ?? client).get<GetRecordingsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/recordings',
    ...options
});

/**
 * Delete a recording
 */
export const deleteRecording = <ThrowOnError extends boolean = false>(options: Options<DeleteRecordingData, ThrowOnError>) => (options.client ?? client).delete<DeleteRecordingResponses, DeleteRecordingErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/recordings/{recordingId}',
    ...options
});

/**
 * Stream recording (deprecated)
 */
export const getRecordingStream = <ThrowOnError extends boolean = false>(options: Options<GetRecordingStreamData, ThrowOnError>) => (options.client ?? client).get<unknown, GetRecordingStreamErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/recordings/{recordingId}/stream',
    ...options
});

/**
 * Get HLS playlist for a recording
 */
export const getRecordingHlsPlaylist = <ThrowOnError extends boolean = false>(options: Options<GetRecordingHlsPlaylistData, ThrowOnError>) => (options.client ?? client).get<GetRecordingHlsPlaylistResponses, GetRecordingHlsPlaylistErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/recordings/{recordingId}/playlist.m3u8',
    ...options
});

/**
 * Get HLS segment for a recording
 */
export const getRecordingHlsCustomSegment = <ThrowOnError extends boolean = false>(options: Options<GetRecordingHlsCustomSegmentData, ThrowOnError>) => (options.client ?? client).get<GetRecordingHlsCustomSegmentResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/recordings/{recordingId}/{segment}',
    ...options
});

/**
 * Create session cookie
 *
 * Exchanges the Bearer token for a secure HttpOnly session cookie, enabling native playback (HLS) without token in URL.
 */
export const createSession = <ThrowOnError extends boolean = false>(options?: Options<CreateSessionData, ThrowOnError>) => (options?.client ?? client).post<CreateSessionResponses, CreateSessionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/session',
    ...options
});

/**
 * List all timers
 */
export const getTimers = <ThrowOnError extends boolean = false>(options?: Options<GetTimersData, ThrowOnError>) => (options?.client ?? client).get<GetTimersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/timers',
    ...options
});

/**
 * Create a timer
 */
export const addTimer = <ThrowOnError extends boolean = false>(options: Options<AddTimerData, ThrowOnError>) => (options.client ?? client).post<AddTimerResponses, AddTimerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/timers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete timer
 */
export const deleteTimer = <ThrowOnError extends boolean = false>(options: Options<DeleteTimerData, ThrowOnError>) => (options.client ?? client).delete<DeleteTimerResponses, DeleteTimerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/timers/{timerId}',
    ...options
});

/**
 * Get timer
 */
export const getTimer = <ThrowOnError extends boolean = false>(options: Options<GetTimerData, ThrowOnError>) => (options.client ?? client).get<GetTimerResponses, GetTimerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/timers/{timerId}',
    ...options
});

/**
 * Edit timer
 */
export const updateTimer = <ThrowOnError extends boolean = false>(options: Options<UpdateTimerData, ThrowOnError>) => (options.client ?? client).patch<UpdateTimerResponses, UpdateTimerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/timers/{timerId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Preview conflicts
 */
export const previewConflicts = <ThrowOnError extends boolean = false>(options: Options<PreviewConflictsData, ThrowOnError>) => (options.client ?? client).post<PreviewConflictsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/timers/conflicts:preview',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get DVR capabilities
 */
export const getDvrCapabilities = <ThrowOnError extends boolean = false>(options?: Options<GetDvrCapabilitiesData, ThrowOnError>) => (options?.client ?? client).get<GetDvrCapabilitiesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/dvr/capabilities',
    ...options
});

/**
 * Get DVR recording status
 */
export const getDvrStatus = <ThrowOnError extends boolean = false>(options?: Options<GetDvrStatusData, ThrowOnError>) => (options?.client ?? client).get<GetDvrStatusResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/dvr/status',
    ...options
});

/**
 * Terminate a stream session
 */
export const deleteStreamsId = <ThrowOnError extends boolean = false>(options: Options<DeleteStreamsIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteStreamsIdResponses, DeleteStreamsIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/streams/{id}',
    ...options
});

/**
 * Get recent logs
 */
export const getLogs = <ThrowOnError extends boolean = false>(options?: Options<GetLogsData, ThrowOnError>) => (options?.client ?? client).get<GetLogsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/logs',
    ...options
});

/**
 * List all series recording rules
 */
export const getSeriesRules = <ThrowOnError extends boolean = false>(options?: Options<GetSeriesRulesData, ThrowOnError>) => (options?.client ?? client).get<GetSeriesRulesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/series-rules',
    ...options
});

/**
 * Create a new series rule
 */
export const createSeriesRule = <ThrowOnError extends boolean = false>(options: Options<CreateSeriesRuleData, ThrowOnError>) => (options.client ?? client).post<CreateSeriesRuleResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/series-rules',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Run a specific series rule immediately
 */
export const runSeriesRule = <ThrowOnError extends boolean = false>(options: Options<RunSeriesRuleData, ThrowOnError>) => (options.client ?? client).post<RunSeriesRuleResponses, RunSeriesRuleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/series-rules/{id}/run',
    ...options
});

/**
 * Run all enabled series rules immediately
 */
export const runAllSeriesRules = <ThrowOnError extends boolean = false>(options?: Options<RunAllSeriesRulesData, ThrowOnError>) => (options?.client ?? client).post<RunAllSeriesRulesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/series-rules/run',
    ...options
});

/**
 * Delete a series rule
 */
export const deleteSeriesRule = <ThrowOnError extends boolean = false>(options: Options<DeleteSeriesRuleData, ThrowOnError>) => (options.client ?? client).delete<DeleteSeriesRuleResponses, DeleteSeriesRuleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/series-rules/{id}',
    ...options
});
