name: Policy Checks (Conftest)

"on":
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'policy/**'
      - '.github/workflows/conftest.yml'
  pull_request:
    paths:
      - 'Dockerfile'
      - 'policy/**'
      - '.github/workflows/conftest.yml'

permissions:
  contents: read

jobs:
  conftest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.51.0/conftest_0.51.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.51.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/
          conftest --version

      - name: Install dockerfile-parser
        run: |
          pip install dockerfile-parse

      - name: Parse Dockerfile for Conftest
        run: |
          python3 << 'EOF'
          import json
          from dockerfile_parse import DockerfileParser

          with open('Dockerfile', 'r') as f:
              dfp = DockerfileParser()
              dfp.content = f.read()

          # Convert to format conftest can work with
          output = []
          for insn in dfp.structure:
              output.append({
                  "Cmd": insn['instruction'].lower(),
                  "Value": insn['value'].split() if insn['value'] else []
              })

          with open('dockerfile.json', 'w') as f:
              json.dump(output, f, indent=2)
          EOF

      - name: Test Dockerfile policies
        run: |
          conftest test dockerfile.json \
            --policy policy/dockerfile.rego \
            --namespace main \
            --all-namespaces

      - name: Test Kubernetes manifests (if exist)
        if: hashFiles('k8s/**/*.yaml') != ''
        run: |
          conftest test k8s/ \
            --policy policy/kubernetes.rego \
            --namespace main \
            --all-namespaces \
            --recursive
