name: Docker Integration Tests (Rust FFI + GPU)

# CRITICAL: These tests verify the full production build including Rust FFI
# Required for live deployment - tests what actually runs in production

on:
  push:
    branches: [main]
    paths:
      - '**/*.go'
      - '**/*.rs'
      - 'Dockerfile'
      - 'transcoder/**'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/docker-integration-tests.yml'
  pull_request:
    branches: [main]
    paths:
      - '**/*.go'
      - '**/*.rs'
      - 'Dockerfile'
      - 'transcoder/**'
  workflow_dispatch:

concurrency:
  group: docker-integration-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  docker-build-and-test:
    name: Build Docker & Run Full Integration Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v5.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349  # v3.7.1
        with:
          driver: docker-container

      - name: Build Docker image to go-builder stage (with tests)
        id: docker_build
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75  # v6.9.0
        env:
          SOURCE_DATE_EPOCH: '0'
        with:
          context: .
          file: Dockerfile
          target: go-builder
          load: true
          tags: xg2g:test-builder
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Verify Docker image was built
        run: |
          docker images
          docker inspect xg2g:test-builder

      - name: Run Go tests inside Docker (with Rust FFI + GPU tags)
        run: |
          set -euo pipefail

          echo "## Docker Integration Test Results" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

          # Run tests with gpu tags inside the go-builder container
          # This tests the ACTUAL production configuration with all dependencies
          docker run --rm --entrypoint sh xg2g:test-builder -c '
            set -euo pipefail
            cd /src
            echo "Testing with GPU tags (Rust FFI enabled)..."

            # Verify Rust library is available
            ls -lh /usr/local/lib/libxg2g_transcoder.so

            # Run all tests with gpu tags
            CGO_ENABLED=1 go test -tags=gpu -v ./... 2>&1 | tee /tmp/test-output.txt
            test_exit=$?

            # Check results
            if [ $test_exit -ne 0 ]; then
              echo "❌ Tests failed with exit code $test_exit"
              exit 1
            fi

            if grep -q "FAIL" /tmp/test-output.txt; then
              echo "❌ Tests contain failures!"
              exit 1
            fi

            echo "✅ All tests passed with Rust FFI!"
          ' || {
            echo "❌ **Docker integration tests FAILED**" >> "$GITHUB_STEP_SUMMARY"
            echo "" >> "$GITHUB_STEP_SUMMARY"
            echo "This means the production build has issues!" >> "$GITHUB_STEP_SUMMARY"
            exit 1
          }

          echo "✅ **All Docker integration tests passed**" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "Production build verified with Rust FFI + GPU transcoding" >> "$GITHUB_STEP_SUMMARY"

      - name: Build final production image (verification)
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75  # v6.9.0
        env:
          SOURCE_DATE_EPOCH: '0'
        with:
          context: .
          file: Dockerfile
          load: true
          tags: xg2g:prod
          cache-from: type=gha
          provenance: false

      - name: Verify Rust library is present in production image
        run: |
          docker run --rm --entrypoint sh xg2g:prod -c '
            set -e
            echo "=== Verifying Rust library artifacts ==="

            # Verify .so file exists and has content
            test -f /app/lib/libxg2g_transcoder.so || (echo "❌ libxg2g_transcoder.so not found" && exit 1)
            test -s /app/lib/libxg2g_transcoder.so || (echo "❌ libxg2g_transcoder.so is empty" && exit 1)

            # Verify dynamic linking (file command not available in Alpine base)
            ldd /app/xg2g | grep -q xg2g_transcoder || (echo "❌ Binary not linked to Rust library" && exit 1)

            # Extended ABI validation (Phase 2)
            echo "=== Extended ABI & Dependency Validation ==="

            # Check SONAME
            readelf -d /app/lib/libxg2g_transcoder.so | grep SONAME || echo "⚠️  No SONAME (OK for FFI lib)"

            # List GLIBC dependencies
            echo "GLIBC dependencies:"
            objdump -T /app/lib/libxg2g_transcoder.so | grep GLIBC_ | awk "{print \$NF}" | sort -uV

            # Verify expected dependencies only
            echo "All dynamic dependencies:"
            ldd /app/lib/libxg2g_transcoder.so | awk "{print \$1}" | sort -u

            echo "✅ ABI validation complete"

            # Show info
            ls -lh /app/lib/libxg2g_transcoder.so
            echo "✅ Rust library artifacts verified successfully"
          '

      - name: Run smoke test of production binary
        run: |
          docker run --rm -e XG2G_DATA=/tmp/test -e XG2G_OWI_BASE=http://example.com xg2g:prod sh -c '
            timeout 5s /app/xg2g || exit_code=$?
            # Exit code 124 = timeout (expected, daemon runs forever)
            # Exit code 1 = config error (also acceptable for this test)
            if [ "${exit_code:-0}" -eq 124 ] || [ "${exit_code:-0}" -eq 1 ]; then
              echo "✅ Binary starts correctly"
              exit 0
            else
              echo "❌ Binary failed with unexpected exit code: $exit_code"
              exit 1
            fi
          '

      - name: Upload build artifacts and logs
        if: always()
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808  # v4.4.3
        with:
          name: docker-integration-logs-${{ github.run_id }}
          path: |
            /tmp/test-output.txt
          retention-days: 21
          if-no-files-found: ignore
          compression-level: 6
          overwrite: false

      - name: Generate test summary
        if: always()
        run: |
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "### Test Configuration" >> "$GITHUB_STEP_SUMMARY"
          echo "- Build tags: \`gpu\`" >> "$GITHUB_STEP_SUMMARY"
          echo "- Rust FFI: ✅ Enabled" >> "$GITHUB_STEP_SUMMARY"
          echo "- GPU Transcoding: ✅ Available" >> "$GITHUB_STEP_SUMMARY"
          echo "- Environment: Docker (production-like)" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "**This test verifies the actual production configuration!**" >> "$GITHUB_STEP_SUMMARY"
