name: Fuzz Testing

"on":
  push:
    branches: [main]
    paths:
      - '**/*_fuzz_test.go'
      - 'internal/**/*.go'
      - '.github/workflows/fuzz.yml'
  pull_request:
    paths:
      - '**/*_fuzz_test.go'
      - 'internal/**/*.go'
      - '.github/workflows/fuzz.yml'
  schedule:
    # Run weekly on Monday at 2am UTC
    - cron: '0 2 * * 1'

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - package: internal/epg
            package_name: internal-epg
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run Fuzz Tests
        env:
          FUZZ_TIME: 30s
        run: |
          cd ${{ matrix.package }}

          # Find all fuzz test functions
          fuzz_funcs=$(go test -list=Fuzz.* | grep -E '^Fuzz')

          if [ -z "$fuzz_funcs" ]; then
            echo "No fuzz tests found in ${{ matrix.package }}"
            exit 0
          fi

          # Run each fuzz test
          for func in $fuzz_funcs; do
            echo "Running $func for $FUZZ_TIME..."
            go test -fuzz=$func -fuzztime=$FUZZ_TIME -v || exit 1
          done

      - name: Upload Crash Artifacts
        if: failure()
        uses: actions/upload-artifact@v5
        with:
          name: fuzz-crashes-${{ matrix.package_name }}
          path: |
            ${{ matrix.package }}/testdata/fuzz/*/
          retention-days: 30
