name: Security - Gitleaks

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  schedule:
    - cron: "23 4 * * 1" # weekly Monday

concurrency:
  group: repo-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  gitleaks:
    name: Scan for Secrets
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # Latest stable
        with:
          fetch-depth: 0 # Full history required

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
