name: PR Conventional Commits Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: read

jobs:
  conventional-commits:
    name: Validate PR Title (Conventional Commits)
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title follows Conventional Commits
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"

          # Conventional Commits pattern:
          # type(optional-scope)(optional-scope)...: description
          # Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
          # Allows multiple scopes (e.g., chore(ci)(deps): ...) for Dependabot PRs
          PATTERN='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9_/-]+\))*: .{1,72}$'

          if ! echo "$PR_TITLE" | grep -Eq "$PATTERN"; then
            echo "❌ PR title does not follow Conventional Commits format"
            echo ""
            echo "Current title:"
            echo "  $PR_TITLE"
            echo ""
            echo "Expected format:"
            echo "  type(scope)(scope)...: description"
            echo ""
            echo "Valid types:"
            echo "  - feat:     New feature"
            echo "  - fix:      Bug fix"
            echo "  - docs:     Documentation changes"
            echo "  - style:    Code style changes (formatting, etc.)"
            echo "  - refactor: Code refactoring"
            echo "  - perf:     Performance improvements"
            echo "  - test:     Adding or updating tests"
            echo "  - build:    Build system changes"
            echo "  - ci:       CI/CD changes"
            echo "  - chore:    Other changes (dependencies, etc.)"
            echo "  - revert:   Revert previous commit"
            echo ""
            echo "Examples:"
            echo "  ✅ feat(api): add health check endpoint"
            echo "  ✅ fix(epg): handle empty programme list"
            echo "  ✅ docs: update deployment guide"
            echo "  ✅ chore(deps): bump Go to 1.24.4"
            echo "  ✅ chore(ci)(deps): bump actions/checkout from 4 to 5"
            echo ""
            exit 1
          fi

          echo "✅ PR title follows Conventional Commits format"
          echo "Title: $PR_TITLE"
