// MECHANICALLY GENERATED by backend/scripts/generate-consumption-types.mjs
// DO NOT EDIT.

export interface NormativeDecision {
    selectedOutputUrl: string;
    selectedOutputKind: string;
    mode: 'direct_play' | 'transcode' | 'deny';
    // Forbidden fields like 'outputs' are NOT here.
}

export interface NormativeResumeSummary {
    posSeconds: number;
    durationSeconds?: number;
    finished?: boolean;
}

export interface NormativePlaybackInfo {
    decision: NormativeDecision;
    isSeekable: boolean;
    durationSeconds?: number;
    resume?: NormativeResumeSummary;
    requestId: string;
    // Legacy URL is NOT here.
}
